const PROPS=[
  {id:1,name:"The Notting Hill Studio",short:"Notting Hill",type:"1 bed · Sleeps 4",emoji:"🏚️",col:"#F5A623",light:"#FEF3DC",border:"#FADDAA",
   desc:"A cosy ground-floor flat behind Portobello Road. Original 1970s fixtures, a temperamental boiler, squeaky floorboards. Enormous potential.",
   upgrades:[
     {id:"fast_wifi",name:"Fibre WiFi 1Gbps",emoji:"📡",desc:"No more WiFi complaints.",cost:150,income:20},
     {id:"smart_tv",name:'Smart TV 65"',emoji:"📺",desc:"4K Netflix & Sky.",cost:180,income:15},
     {id:"coffee_machine",name:"Barista coffee machine",emoji:"☕",desc:"Nespresso + oat milk. Guests rave.",cost:120,income:15},
     {id:"premium_bedding",name:"Hotel-grade bedding",emoji:"🛏️",desc:"400-thread Egyptian cotton.",cost:100,income:20},
     {id:"smart_lock",name:"Smart lock",emoji:"🔐",desc:"Keyless entry. Eliminates check-in complaints.",cost:180,income:10},
     {id:"air_purifier",name:"Air purifier",emoji:"💨",desc:"No more musty smells.",cost:90,income:10},
     {id:"artwork",name:"Statement artwork",emoji:"🖼️",desc:"Guests always photograph it.",cost:80,income:10},
     {id:"boiler",name:"New combi boiler",emoji:"🔥",desc:"Reliable hot water always.",cost:250,income:25},
     {id:"welcome_pack",name:"Welcome pack",emoji:"🎁",desc:"Tea, biscuits, local guide. First impressions.",cost:60,income:10},
   ]},
  {id:2,name:"The Shoreditch Loft",short:"Shoreditch",type:"2 bed · Sleeps 5",emoji:"🏢",col:"#6AAF2E",light:"#EAF3DE",border:"#C0DD97",
   desc:"Converted warehouse with exposed brick and high ceilings. Second bedroom needs work, bathroom grout questionable, heating optional in winter.",
   upgrades:[
     {id:"fast_wifi_2",name:"Fibre WiFi 1Gbps",emoji:"📡",desc:"Essential at this level.",cost:150,income:25},
     {id:"second_bed",name:"Luxury second bedroom",emoji:"🛏️",desc:"Proper bed, nightstands, reading lights.",cost:220,income:30},
     {id:"dishwasher",name:"Dishwasher",emoji:"🍽️",desc:"Guests expect it at this price point.",cost:180,income:20},
     {id:"smart_tv_2",name:"Two smart TVs",emoji:"📺",desc:"One per bedroom.",cost:280,income:25},
     {id:"heating_fix",name:"New heating system",emoji:"🔥",desc:"Warm flat, happy guests.",cost:300,income:30},
     {id:"bathroom_reno",name:"Bathroom renovation",emoji:"🚿",desc:"Rainfall shower, new tiles.",cost:350,income:35},
     {id:"record_player",name:"Vinyl record player",emoji:"🎵",desc:"Curated collection included.",cost:130,income:20},
     {id:"rooftop",name:"Rooftop terrace access",emoji:"🌆",desc:"City views. Huge USP.",cost:400,income:40},
     {id:"noise_sensor",name:"Noise monitoring system",emoji:"📢",desc:"Auto-alerts at 80dB. Catches parties early.",cost:280,income:30},
   ]},
  {id:3,name:"The Chelsea Townhouse",short:"Chelsea",type:"3 bed · Sleeps 6",emoji:"🏘️",col:"#1C2280",light:"#EEF0FA",border:"#C5CAFE",
   desc:"Victorian terraced townhouse over three floors. Impeccable architecture, kitchen from 2003, one windowless bathroom, overgrown garden.",
   upgrades:[
     {id:"kitchen_reno",name:"Full kitchen renovation",emoji:"🍳",desc:"Smeg appliances, marble worktops.",cost:500,income:50},
     {id:"garden_land",name:"Garden landscaping",emoji:"🌸",desc:"Bistro set, fairy lights, BBQ.",cost:300,income:35},
     {id:"smart_home",name:"Smart home system",emoji:"🏠",desc:"Voice control — lights, heating, blinds.",cost:400,income:40},
     {id:"cinema",name:"Cinema room",emoji:"🎬",desc:"Projector + surround sound.",cost:450,income:45},
     {id:"lux_baths",name:"Luxury bathrooms ×2",emoji:"🛁",desc:"Roll-top baths.",cost:600,income:60},
     {id:"concierge",name:"Concierge service",emoji:"🎩",desc:"Local tips, reservations, transfers.",cost:350,income:40},
     {id:"gym",name:"Home gym corner",emoji:"💪",desc:"Peloton + weights.",cost:280,income:30},
     {id:"wine_fridge",name:"Wine fridge (stocked)",emoji:"🍷",desc:"Welcome bottle for every guest.",cost:200,income:25},
     {id:"multi_lang",name:"Multilingual cleaning team",emoji:"🌍",desc:"Translates instructions instantly.",cost:380,income:40},
   ]},
  {id:4,name:"The Mayfair Penthouse",short:"Mayfair",type:"4 bed · Sleeps 8",emoji:"🏙️",col:"#F5A623",light:"#FEF3DC",border:"#FADDAA",
   desc:"Top-floor apartment with sweeping Hyde Park views. Corporate bookings, celebrities, HNWI guests. Spectacular bones — needs curation and elite service.",
   upgrades:[
     {id:"smart_home_2",name:"Full smart home",emoji:"🏠",desc:"Crestron automation throughout.",cost:800,income:80},
     {id:"home_cinema",name:"Private cinema",emoji:"🎬",desc:"10-seat 4K laser projector.",cost:700,income:70},
     {id:"chef_kitchen",name:"Chef's kitchen",emoji:"👨‍🍳",desc:"La Cornue range. Sub-Zero fridge.",cost:900,income:90},
     {id:"spa_bath",name:"Spa bathroom suite",emoji:"🛁",desc:"Hammam, rain shower, heated floors.",cost:600,income:60},
     {id:"butler",name:"On-call butler",emoji:"🎩",desc:"Pre-arrival shopping, daily service.",cost:500,income:55},
     {id:"transfer",name:"Chauffeur transfer service",emoji:"🚗",desc:"Meet & greet every booking.",cost:400,income:45},
     {id:"art",name:"Curated art collection",emoji:"🖼️",desc:"On loan from Saatchi Gallery.",cost:600,income:60},
     {id:"wine_cellar",name:"Wine cellar 200 bottles",emoji:"🍷",desc:"Sommelier-curated. Guests rave.",cost:500,income:55},
     {id:"payment_pro",name:"Premium payment processor",emoji:"💳",desc:"Stripe Premium. Cards never decline.",cost:450,income:50},
   ]},
  {id:5,name:"The Kensington Mansion",short:"Kensington",type:"5 bed · Sleeps 10",emoji:"🏰",col:"#1C2280",light:"#EEF0FA",border:"#C5CAFE",
   desc:"A Grade II listed Regency mansion. Royalty has slept here. Film crews have shot here. Make it the most sought-after short-let in London.",
   upgrades:[
     {id:"michelin_kitchen",name:"Michelin-standard kitchen",emoji:"👨‍🍳",desc:"Built by a 3-star consultant.",cost:1200,income:120},
     {id:"cinema20",name:"Private cinema 20 seats",emoji:"🎬",desc:"Dolby Atmos. Red velvet seating.",cost:1000,income:100},
     {id:"pool",name:"Indoor pool & spa",emoji:"🏊",desc:"Heated, with sauna & steam room.",cost:1500,income:150},
     {id:"full_butler",name:"Full butler household",emoji:"🎩",desc:"Butler, chef, housekeeper, driver.",cost:800,income:90},
     {id:"helipad",name:"Rooftop helipad",emoji:"🚁",desc:"HEMS certified. Guests arrive in style.",cost:1000,income:100},
     {id:"art_gallery",name:"Private art gallery wing",emoji:"🖼️",desc:"Rotating exhibitions.",cost:900,income:95},
     {id:"studio",name:"Recording studio",emoji:"🎙️",desc:"SSL console. Fully soundproofed.",cost:800,income:85},
     {id:"vault",name:"Secure vault room",emoji:"🔒",desc:"For guests' valuables. Peace of mind.",cost:600,income:70},
     {id:"stables",name:"Equestrian stables",emoji:"🐎",desc:"For Kensington's pony-set guests.",cost:1100,income:110},
   ]},
  {id:6,name:"The Covent Garden Royal Penthouse",short:"Covent Garden",type:"6 bed · Sleeps 14",emoji:"👑",col:"#8B0000",light:"#F8E5E5",border:"#E8B5B5",
   desc:"London's most exclusive short-let. Two-storey penthouse above the Royal Opera House, private rooftop garden overlooking the Piazza, accessed by a discreet private lift. Heads of state. Oscar winners. This is the apex.",
   upgrades:[
     {id:"royal_kitchen",name:"Two Michelin chefs on retainer",emoji:"👨‍🍳",desc:"Michel Roux Jr. and team available 24/7.",cost:2000,income:200},
     {id:"opera_terrace",name:"Opera House terrace",emoji:"🎭",desc:"Private terrace overlooking Covent Garden Piazza.",cost:1800,income:180},
     {id:"private_elevator",name:"Private lift & lobby",emoji:"🛗",desc:"Dedicated entrance. No public corridors. Total privacy.",cost:1500,income:160},
     {id:"royal_suite",name:"Royal master suite",emoji:"👑",desc:"800 sq ft suite with adjacent dressing room and study.",cost:2200,income:220},
     {id:"diplomatic_security",name:"Diplomatic security team",emoji:"🛡️",desc:"Ex-RaSP officers. Discreet. Armed.",cost:1800,income:190},
     {id:"infinity_pool",name:"Rooftop infinity pool",emoji:"🏊",desc:"Heated. Glass-walled. Skyline views.",cost:2500,income:250},
     {id:"private_theatre",name:"Private theatre",emoji:"🎭",desc:"40-seat. West End productions performed privately.",cost:2400,income:240},
     {id:"royal_garage",name:"Underground supercar garage",emoji:"🏎️",desc:"6 spaces. Trickle-charging. Detailing service.",cost:1700,income:175},
     {id:"royal_wine",name:"Pre-revolutionary cellar",emoji:"🍷",desc:"Vintages from 1789. Insured at £2.4m.",cost:2000,income:200},
   ]},
];
