const ALL_QUESTIONS = {
  1: [
    {guest:"Sarah M.",mood:"anxious 😟",icon:"😟",drama:false,scenario:"11 PM. Sarah messages: 'The WiFi keeps cutting out and I have a 7 AM video call with my CEO. I cannot fail this meeting.'",options:[
      {text:"Reply instantly, walk her through the router fix step-by-step, share your hotspot as a backup",pts:150,good:true,reaction:"Sarah passes her call with flying colours. Her 5-star review specifically names you. 'Best host I've ever had.'"},
      {text:"Promise to sort it first thing in the morning",pts:-80,good:false,reaction:"Sarah calls Airbnb at midnight. A formal complaint is logged against your account."},
      {text:"Send a £20 goodwill gesture and go back to sleep",pts:-60,good:false,reaction:"She takes the money but leaves 3 stars. 'WiFi useless, host unbothered.' Brutal."},
      {text:"Ignore the message — it's 11 PM",pts:-200,good:false,reaction:"Sarah calls Airbnb, gets relocated to a hotel, and the cost is billed back to you. £380 gone."},
    ],tip:"A responsive host at 11 PM is worth more than any amenity. Speed + solution = 5 stars every time."},
    {guest:"The Patels",mood:"oblivious 😶",icon:"😶",drama:false,scenario:"Check-out was 11 AM. It's noon. The Patels are still inside taking selfies in every room. Your cleaner is waiting outside and your next guest arrives at 3 PM.",options:[
      {text:"Message through Airbnb to document it, then call them directly and be warm but firm",pts:120,good:true,reaction:"They're mortified and out in 15 minutes. Documented, resolved, cleaners in. Next guest arrives to a spotless flat."},
      {text:"Tell the cleaner to come back in two hours and hope for the best",pts:-100,good:false,reaction:"The next guest arrives to an uncleaned flat. 1-star review. 'Filthy. Clearly not ready.' Airbnb contacts you."},
      {text:"Call Airbnb and ask them to handle it",pts:-40,good:false,reaction:"Airbnb takes 40 minutes to respond. Your cleaner leaves. You're scrambling solo."},
      {text:"Wait outside awkwardly and hope they notice you",pts:-60,good:false,reaction:"They don't notice. You stand there for 45 minutes. No documentation. Not a great look."},
    ],tip:"Log overstays on Airbnb first — it creates a paper trail you'll need if you ever need to claim compensation."},
    {guest:"Marco T.",mood:"disappointed 😐",icon:"😐",drama:false,scenario:"Marco leaves a 3-star review: 'Perfectly fine flat but the boiler made terrifying noises all night and the WiFi dropped constantly. Host was unresponsive.' It's now public.",options:[
      {text:"Reply publicly: acknowledge both issues, confirm they're now fixed, thank him sincerely",pts:130,good:true,reaction:"Three prospective guests read the exchange and book you specifically because of how you handled it. Conversion gold."},
      {text:"Reply defensively: 'The boiler was professionally serviced last month'",pts:-120,good:false,reaction:"Marco replies back. Now it's a public argument. Two bookings cancel. Airbnb flags the exchange."},
      {text:"Report the review to Airbnb as inaccurate",pts:-150,good:false,reaction:"Airbnb investigates and finds the review perfectly valid. They issue you a warning for review manipulation."},
      {text:"Leave it — 3 stars isn't that bad",pts:-50,good:false,reaction:"No host response = disengaged host. Your search ranking drops. Three consecutive 3-stars and you lose Superhost status."},
    ],tip:"Your public response to bad reviews is read by every future guest. Gracious and solution-focused always wins."},
    {guest:"Tom & Anya",mood:"excited 😄",icon:"😄",drama:false,scenario:"Your cleaner texts at 10 AM: 'So sorry, family emergency, can't come today.' Check-in is at 3 PM. Tom and Anya are flying in from Berlin.",options:[
      {text:"Call every cleaner you know, post on local groups offering a premium rate, clean it yourself if needed",pts:140,good:true,reaction:"You pull it off. Tom and Anya check in to a spotless flat. They leave 5 stars. They never knew."},
      {text:"Cancel the booking citing 'maintenance emergency'",pts:-300,good:false,reaction:"Tom and Anya's Berlin trip is ruined. Airbnb hits you with a host-cancellation penalty. Your calendar is blocked for 30 days."},
      {text:"Let them check in and apologise for 'a few things'",pts:-180,good:false,reaction:"'A few things' is a dirty bathroom, used towels, and crumbs everywhere. 1-star review with photos. Full refund demanded."},
      {text:"Delay check-in by 2 hours, message apologetically, offer a £30 voucher",pts:60,good:true,reaction:"They're mildly annoyed but understanding. 'Host communicated well and was apologetic.' 4 stars."},
    ],tip:"Every host needs a backup cleaner list of at least 3 people. Build it before you ever need it."},
    {guest:"Beatrice H.",mood:"hopeful 🦚",icon:"🦚",drama:false,scenario:"Beatrice sends a pre-stay message: 'Hi! My emotional support peacock, Sir Reginald, helps with my anxiety. He's very well-behaved. Is it okay if he joins me? Your listing says no pets.'",options:[
      {text:"Politely decline — your no-pets policy covers all animals, including Sir Reginald",pts:100,good:true,reaction:"Beatrice accepts graciously. 'Fair enough! See you soon.' No drama. 5-star stay."},
      {text:"Say yes — it's just a bird, how bad can it be?",pts:-200,good:false,reaction:"Sir Reginald destroys your sofa cushions, terrifies your upstairs neighbour, and leaves a deposit on the kitchen floor. £340 in damages."},
      {text:"Check with Airbnb on ESA policy first, then decline",pts:130,good:true,reaction:"Correct approach. ESAs don't carry the same rights as service animals in UK short-lets. Professionally handled. Beatrice books anyway without Sir Reginald."},
      {text:"Charge a £200 peacock deposit and say yes",pts:-70,good:false,reaction:"Beatrice leaves a 2-star review: 'Host nickel-and-dimed me over my support animal. Shameful.'"},
    ],tip:"Emotional support animals don't carry the same legal weight as service animals in UK short-term rentals. Your no-pets policy stands."},
    {guest:"Derek F.",mood:"furious 😡",icon:"😡",drama:true,scenario:"Derek checks in at 9 PM and immediately calls you: 'The flat smells like something died here. I am NOT staying here. My wife is in tears. We have a baby. I'm calling Airbnb right now.'",options:[
      {text:"Rush over personally, assess the situation, call an emergency cleaning service, offer alternative accommodation",pts:200,good:true,reaction:"You arrive in 25 minutes. It's a blocked drain — sorted in an hour. Derek's wife is genuinely moved by your response. 4-star review, glowing comments about your professionalism."},
      {text:"Tell him you'll send someone tomorrow morning",pts:-250,good:false,reaction:"Derek calls Airbnb, who relocate his family to a hotel. The £480 hotel bill is charged to you. Plus a 1-star review. Plus a formal complaint."},
      {text:"Apologise profusely but say there's nothing you can do tonight",pts:-180,good:false,reaction:"Airbnb steps in. Full refund issued. Account warning. 'Host left family with baby in uninhabitable property.'"},
      {text:"Offer Derek a £50 refund and suggest he opens a window",pts:-220,good:false,reaction:"Derek goes ballistic. Screenshots your message and posts it publicly. National press picks it up. Worst outcome possible."},
    ],tip:"Guest emergencies require immediate personal involvement. Being present and solving problems is the most powerful thing a host can do."},
    {guest:"Priya K.",mood:"suspicious 🧐",icon:"🧐",drama:false,scenario:"Priya messages before check-in: 'Is it actually quiet? The previous reviews mention noise from the pub below. I'm a very light sleeper and I have an early start every day.'",options:[
      {text:"Be honest: 'Friday nights can get lively until midnight. Here's what I've done to mitigate it — blackout blinds, earplugs in the welcome pack, and a white noise machine.'",pts:140,good:true,reaction:"Priya appreciates the honesty enormously. 'Host was upfront. Earplugs were a lifesaver. Will definitely return.' 5 stars."},
      {text:"Say it's completely quiet — it'll probably be fine",pts:-160,good:false,reaction:"Friday is chaos. Priya messages furiously at midnight. Demands a refund. Leaves a 1-star review calling you 'dishonest'."},
      {text:"Tell her to book somewhere else if noise is a concern",pts:-80,good:false,reaction:"Priya screenshots your response, shares it in a travel group. 'The rudest host I've ever encountered.' Viral. Devastating."},
      {text:"Offer her a 10% discount to acknowledge the potential noise",pts:80,good:true,reaction:"Priya books, sleeps through it with earplugs, and leaves 4 stars. 'Fair and transparent host.'"},
    ],tip:"Honesty about property quirks — paired with practical solutions — builds more trust than false promises ever could."},
    {guest:"The Hendersons",mood:"confused 😕",icon:"😕",drama:false,scenario:"The Henderson family (2 adults, 3 kids) arrives and the father calls you: 'We can't find the keys. There's nothing in the lockbox. We've been standing in the rain for 20 minutes with three wet children.'",options:[
      {text:"Drop everything, call a locksmith, head there yourself with a spare key set, send an apology gift",pts:180,good:true,reaction:"You arrive in 22 minutes with keys and a bag of snacks for the kids. The Hendersons are completely won over. 5 stars. 'Went above and beyond in an awful situation.'"},
      {text:"Try to talk them through finding the lockbox via phone for another 30 minutes",pts:-60,good:false,reaction:"The code was right but the box had jammed. 50 minutes in the rain. Three unhappy children. 2 stars."},
      {text:"Tell them the code again and hope for the best",pts:-100,good:false,reaction:"Still doesn't work. They call Airbnb. Your response log shows you gave instructions twice and did nothing else. Not a good look."},
      {text:"Call a local neighbour with a spare key to help immediately",pts:120,good:true,reaction:"Neighbour arrives in 8 minutes. Problem solved. Hendersons rate the 'incredible community spirit' in their 5-star review. Creative solution."},
    ],tip:"Always have a physical backup key solution. Smart locks with code backups are the gold standard — never rely on one access method."},
  ],
  2: [
    {guest:"The Okafor Group",mood:"disappointed 😤",icon:"😤",drama:false,scenario:"The Okafor Group (5 colleagues, work trip) messages at 10 PM on night one: 'The second bedroom is a mattress on the floor with no pillow cases. Our director is sleeping on it. This is embarrassing for all of us.'",options:[
      {text:"Apologise unreservedly, offer a meaningful partial refund, send an emergency linen delivery tonight",pts:160,good:true,reaction:"Linen arrives at 11 PM. The director is impressed. 4-star review: 'Host remedied an embarrassing situation with genuine class.'"},
      {text:"Dispute it — the listing said 'basic second bedroom'",pts:-180,good:false,reaction:"The Okafor Group escalates to Airbnb. Full refund issued. 1-star review with photos of the mattress. Your listing is temporarily suspended for misrepresentation."},
      {text:"Offer a £30 token refund",pts:-80,good:false,reaction:"'£30 for our director sleeping on a bare mattress? Insulting.' 1-star review. Airbnb complaint."},
      {text:"Upgrade the room immediately for future guests, offer nothing now",pts:-40,good:false,reaction:"Too little too late. 3-star review. 'At least it won't happen to the next person.'"},
    ],tip:"Your listing photos and descriptions must match reality. The gap between expectation and experience is where reviews are destroyed."},
    {guest:"Deloitte Team",mood:"professional 💼",icon:"💼",drama:false,scenario:"Rebecca from Deloitte calls: 'We want to block your Shoreditch loft for our visiting team every month — 5 nights a time. But we need 30% off your standard rate. What can you do?'",options:[
      {text:"Counter with 20% and a guaranteed block-booking agreement. Shake on it.",pts:200,good:true,reaction:"Deal closed. Guaranteed monthly income. Less turnover. Deloitte becomes your most reliable client. You raise your standard rate 15% within a month."},
      {text:"Decline politely — your rates are your rates",pts:-60,good:false,reaction:"Deloitte books a serviced apartment down the road. You miss £3,200/month in guaranteed income. Competitor gains a reliable anchor client."},
      {text:"Accept the full 30% immediately",pts:80,good:true,reaction:"Income secured, though you left money on the table. Deloitte are delighted. Regular income begins."},
      {text:"Say you'll think about it and come back to them",pts:-80,good:false,reaction:"Rebecca moves on. She can't wait. Corporate clients expect decisions. Opportunity gone."},
    ],tip:"Corporate long-stay bookings are gold — less turnover, professional guests, predictable income. Negotiate confidently, don't refuse flatly."},
    {guest:"Smoke & Mirrors",mood:"gone 🚬",icon:"🚬",drama:false,scenario:"Your cleaner calls after a checkout: 'The whole flat reeks of cigarettes. Walls, curtains, everything. It'll take a deep clean and repainting. I'd estimate £600 minimum.' Your listing is strictly non-smoking.",options:[
      {text:"Photograph and video everything within the hour, file an Airbnb damage claim with full evidence, book specialist cleaners",pts:180,good:true,reaction:"Airbnb rules in your favour. The full £600 is covered. Your evidence was watertight. The guests are permanently banned from the platform."},
      {text:"Air it out for a few days and hope the smell fades",pts:-120,good:false,reaction:"Next guests arrive to a lingering smoke smell. 2-star review. £0 recovered. And now you need the deep clean anyway."},
      {text:"Message the guests angrily demanding immediate payment",pts:-80,good:false,reaction:"They deny everything. Without documentation, Airbnb can't rule in your favour. You get nothing."},
      {text:"Write them a scathing public review and move on",pts:-60,good:false,reaction:"Cathartic but financially useless. You still need to spend £600 on cleaning. Document first — always."},
    ],tip:"Damage claims live or die on evidence. Photos with timestamps within an hour of checkout are your entire case."},
    {guest:"Léa D.",mood:"loving it 🥰",icon:"🥰",drama:false,scenario:"Léa has been staying for 10 days and loves the loft. She messages: 'Is there any chance I can extend by 5 nights? I know it's last minute. I'll pay full rate.' You have a booking starting in 3 days.",options:[
      {text:"Apologise warmly — you have a confirmed booking. Suggest she books your Notting Hill property instead.",pts:130,good:true,reaction:"Léa books your other property. You've just executed your first successful cross-sell. New guests arrive at Shoreditch to a pristine flat."},
      {text:"Cancel the upcoming booking to accommodate Léa — she's been a dream guest",pts:-280,good:false,reaction:"The incoming guests are devastated. Airbnb hits you with the maximum host-cancellation penalty. Your Superhost status is suspended. Léa is horrified when she finds out."},
      {text:"Tell Léa she can stay an extra 2 nights (not 5) as a compromise",pts:-100,good:false,reaction:"This means the next guests' check-in overlaps. Chaos ensues. Two sets of guests, one flat, one very bad evening."},
      {text:"Contact the incoming guests and offer them £200 compensation to rebook",pts:-60,good:false,reaction:"They decline. They've already booked flights. You've now created two unhappy parties simultaneously."},
    ],tip:"Never cancel a confirmed booking. The penalties, trust damage, and review consequences are catastrophic. Cross-sell to your other properties instead."},
    {guest:"Jake & The Lads",mood:"party mode 🎉",icon:"🎉",drama:true,scenario:"It's 1 AM. Your downstairs neighbour calls you: 'Your guests have had 30 people in that flat since 10 PM. Music is shaking my ceiling. I'm calling the council if this isn't sorted in 10 minutes.'",options:[
      {text:"Call the guests immediately: 'All additional guests must leave now or I'm terminating the booking and calling the police.' No negotiation.",pts:200,good:true,reaction:"Jake panics and clears the flat within 8 minutes. Neighbour is satisfied. You document everything. Jake checks out early the next morning. You file a claim for the mess."},
      {text:"Send a polite message asking them to keep it down a little",pts:-180,good:false,reaction:"They ignore it. Council noise officer arrives. Your property is formally flagged. Your short-let licence comes under review."},
      {text:"Call the police directly and let them handle it",pts:80,good:true,reaction:"Bold but effective. Party cleared. Neighbour satisfied. Though the guests leave a furious 1-star review calling you 'trigger-happy'. You counter it professionally."},
      {text:"Ignore it — it's not technically your problem after hours",pts:-300,good:false,reaction:"Council noise officer arrives. Property flagged. Neighbour sues for disturbance. Your short-let licence is revoked. Game-changing mistake."},
    ],tip:"Unauthorised parties are grounds for immediate booking termination on Airbnb. Don't negotiate — act decisively and document everything."},
    {guest:"The Silent Guest",mood:"fine apparently 🤷",icon:"🤷",drama:false,scenario:"A guest stays 7 nights, says nothing throughout, then leaves a 2-star review: 'The shower ran cold after 5 minutes every day. The heating took an hour to kick in. Wouldn't return.' You had no idea about either issue.",options:[
      {text:"Reply publicly, thank them for the feedback, explain both issues are now fixed, invite them to return at a discount",pts:150,good:true,reaction:"Two future guests read the exchange and book specifically because they see you're responsive and fix problems. Net positive."},
      {text:"Reply asking why they didn't mention it during their stay so you could have fixed it",pts:-40,good:false,reaction:"Comes across as defensive. 'Why didn't you tell me?' shifts blame to the guest. Future guests don't like it."},
      {text:"Contact Airbnb to see if the review can be removed",pts:-140,good:false,reaction:"It can't — it's factually accurate. Airbnb issues you a warning for attempting to remove a legitimate review."},
      {text:"Leave it — 2 stars from a non-communicative guest isn't your fault",pts:-80,good:false,reaction:"No response = no accountability. Future guests have no evidence you care. Bookings decline."},
    ],tip:"Always follow up mid-stay. A simple 'how's everything going?' message on day 2 would have caught both issues before checkout."},
    {guest:"Francesca T.",mood:"influencer 📸",icon:"📸",drama:true,scenario:"Francesca is a travel influencer with 800k followers. After checkout she messages: 'I'd love to feature your loft in a reel — but I need a 50% refund on my stay in exchange for the exposure.'",options:[
      {text:"Decline the refund but offer a complimentary one-night stay for a dedicated feature shoot instead",pts:160,good:true,reaction:"Francesca loves the counter-offer. The reel goes live. Bookings spike 40% in the following week. You've turned a cheeky ask into a marketing win."},
      {text:"Give her the 50% refund — 800k followers is massive reach",pts:-80,good:false,reaction:"The reel gets 12k views, not 800k. She didn't disclose it was an ad. One booking results. You lost £175 for essentially nothing."},
      {text:"Tell her exposure doesn't pay the mortgage and decline entirely",pts:80,good:true,reaction:"Francesca respects the boundary. Posts a genuine unpaid mention anyway. 'Loved this place.' Authentic content performs better than paid."},
      {text:"Ask her to send her media kit and analytics before deciding",pts:120,good:true,reaction:"Smart. You discover her engagement rate is 0.8% — very low for 800k. You negotiate a much smaller gesture. Business savvy at its finest."},
    ],tip:"Influencer partnerships can be valuable — but always ask for analytics, not just follower counts. Engagement rate matters far more than audience size."},
    {guest:"Mr Yamazaki",mood:"precise 🧐",icon:"🧐",drama:false,scenario:"Japanese businessman Mr Yamazaki messages after his first night: 'The pillows are too soft, the shower pressure is insufficient, and the blinds do not fully block the morning light. I require these resolved before tomorrow.'",options:[
      {text:"Source firmer pillows and a shower head upgrade that afternoon, install a blackout blind same day",pts:180,good:true,reaction:"Mr Yamazaki messages: 'Thank you. This is professional hosting.' He books your property directly for his next 6 London visits. He becomes your single most valuable repeat guest."},
      {text:"Apologise but explain you can't change furnishings mid-stay",pts:-60,good:false,reaction:"Mr Yamazaki checks out a day early. 2-star review: 'Unresponsive to reasonable requests.' He books a hotel for future visits."},
      {text:"Offer him a 20% refund as acknowledgement",pts:40,good:true,reaction:"Accepted graciously. Not the ideal resolution, but he appreciates the gesture. 3 stars. 'Host tried.'"},
      {text:"Tell him these are standard furnishings and he's welcome to adjust the blinds himself",pts:-120,good:false,reaction:"Mr Yamazaki has hosted 47 Airbnb stays globally. He knows exactly what good hosting looks like. 1-star review. Airbnb shares it prominently."},
    ],tip:"Detail-oriented guests are your most powerful brand ambassadors when they're delighted — and your most damaging critics when they're not."},
  ],
  3: [
    {guest:"The Williams Family",mood:"casual 😅",icon:"😅",drama:true,scenario:"A family books for 6. You receive a message at midnight before check-in day: 'Quick update — there'll actually be 11 of us. My mum and three cousins decided to join last minute. Hope that's okay!'",options:[
      {text:"Call immediately: 'I'm sorry — the booking is for 6. 11 people exceeds our capacity and insurance limit. We'll need to find an alternative solution together.'",pts:160,good:true,reaction:"You help them find an overflow Airbnb two streets away for the extra 5. They split the group, both properties get used, and you get a grateful 5-star review for your problem-solving."},
      {text:"Say nothing and let all 11 in — it's just one night",pts:-220,good:false,reaction:"Insurance void. A child trips and breaks their wrist on the stairs. You are personally liable. Your short-let licence is suspended pending investigation."},
      {text:"Cancel the booking entirely the morning of check-in",pts:-280,good:false,reaction:"Family of 11 stranded with nowhere to go. Airbnb maximum cancellation penalty applied. Permanent mark on your hosting record."},
      {text:"Charge a per-person supplement for the extra 5 guests",pts:100,good:true,reaction:"Family agrees and pays. You document the agreement through Airbnb. Pragmatic, revenue-positive, and within rules."},
    ],tip:"Occupancy limits aren't arbitrary — they're set by your insurance and fire safety certificate. Exceeding them invalidates both."},
    {guest:"Vision Media",mood:"professional 🎥",icon:"🎥",drama:false,scenario:"A production company wants to use your Chelsea townhouse to film a luxury property advert. One day. They'll pay £4,500. They want an answer today.",options:[
      {text:"Request a full production brief, get a contract and £2,000 damage bond, verify their insurance, then agree",pts:250,good:true,reaction:"The shoot goes perfectly. Property returned immaculate. £4,500 cleared. The director asks to use it for a second campaign next month."},
      {text:"Say yes immediately — £4,500 for one day is incredible",pts:-100,good:false,reaction:"A lighting rig scratches your newly refinished hardwood floor. No contract means no recourse. £780 repair bill. Net: £3,720."},
      {text:"Decline — too much risk for your property",pts:-40,good:false,reaction:"Low-risk, high-reward opportunity passed. With a proper contract, the risk was minimal. £4,500 left on the table."},
      {text:"Ask Airbnb for guidance on commercial shoots first",pts:140,good:true,reaction:"Smart. Airbnb provides clear guidelines. You proceed correctly with proper documentation. Full rate received."},
    ],tip:"Commercial shoots require their own insurance certificate, a damage bond of at least 20% of the day rate, and a production brief. Non-negotiable."},
    {guest:"Multiple guests",mood:"disappointed 🌿",icon:"🌿",drama:false,scenario:"Your third consecutive guest mentions the garden in their review: 'The overgrown garden was a real shame — it clearly has potential but felt unloved and a bit embarrassing.' You've now had 4 garden complaints in 6 weeks.",options:[
      {text:"Spend £350 on professional landscaping, get before/after photos, update the listing with a 'Newly landscaped garden' feature",pts:180,good:true,reaction:"The next 6 reviews all mention the garden positively. It becomes your listing's most-photographed feature. Average nightly rate increases by £22."},
      {text:"Add 'rustic garden charm' to the listing description",pts:-60,good:false,reaction:"5th complaint arrives within two weeks. Airbnb emails you about 'consistent quality concerns'. Listing visibility reduced."},
      {text:"Ignore it — outdoor spaces are seasonal",pts:-100,good:false,reaction:"Airbnb flags your listing after the 6th complaint. Quality review initiated. Listing temporarily suspended."},
      {text:"Mow the lawn and call it done",pts:80,good:true,reaction:"Complaints reduce. Not a 5-star garden, but no longer a talking point. A holding measure while you plan the full upgrade."},
    ],tip:"In a competitive market like Chelsea, outdoor space is a key differentiator. A well-presented garden can justify a 15–20% rate premium."},
    {guest:"The Bellingham-Smyths",mood:"entitled 😤",icon:"😤",drama:true,scenario:"The Bellingham-Smyths arrive and immediately call you: 'There's no Nespresso machine, no fresh flowers, and the bath towels are not hotel-grade. We specifically expect five-star standards and this simply isn't that. We want a 30% refund immediately.'",options:[
      {text:"Calmly explain what is included vs their expectations, offer a goodwill gesture (Nespresso pods delivered, flowers ordered), but firmly decline the refund",pts:160,good:true,reaction:"They accept the gesture. Their review is 3 stars but mentions 'host responded reasonably.' You update your listing to clearly set expectations. Future guests self-filter."},
      {text:"Give them the 30% refund to avoid the confrontation",pts:-100,good:false,reaction:"They pocket the refund and leave a 2-star review anyway. 'Below expectations.' You paid for the privilege of a bad review."},
      {text:"Tell them your listing accurately reflects the property and end the conversation",pts:-80,good:false,reaction:"They call Airbnb. Airbnb reviews your listing. Though technically you're right, the complaint process is a 3-week nightmare."},
      {text:"Send fresh flowers, Nespresso machine, and upgrade their towels within 2 hours",pts:120,good:true,reaction:"They are completely disarmed. 4-star review: 'Host went above and beyond when we raised concerns.' An expensive lesson in managing expectations, but a win."},
    ],tip:"Clear listing descriptions are your best defence against entitled guests. Set expectations precisely — and then exceed them."},
    {guest:"Isabelle R.",mood:"sociable 🍽️",icon:"🍽️",drama:false,scenario:"Isabelle messages: 'Would it be okay to host a small dinner for 10 friends on Saturday? I cook professionally — I'd love to show off your gorgeous kitchen. Happy to leave the place spotless.'",options:[
      {text:"Check your insurance (covers up to 12 visitors), confirm in writing on Airbnb, take a £200 event deposit, say yes",pts:160,good:true,reaction:"Isabelle cooks an extraordinary dinner. She leaves the kitchen cleaner than she found it. 5-star review with photos of the table setting. Your kitchen becomes a listing highlight."},
      {text:"Say yes without any formal agreement",pts:-100,good:false,reaction:"Someone spills red wine on the white sofa. No deposit means no coverage. £420 reupholstering cost falls entirely on you."},
      {text:"Say no — it's a holiday rental not a dining venue",pts:50,good:true,reaction:"Reasonable and safe. Isabelle accepts gracefully. Stays without incident. 4 stars."},
      {text:"Say yes but secretly check in via doorbell camera throughout the evening",pts:-200,good:false,reaction:"Isabelle's friend notices the camera trigger light. Isabelle reports you to Airbnb for unauthorised surveillance during the event. Account suspended."},
    ],tip:"Hosted events can be income-positive and review-positive — with the right paperwork. Insurance check, written confirmation, deposit. Always."},
    {guest:"Lady Pemberton",mood:"formal 🎩",icon:"🎩",drama:true,scenario:"A personal assistant calls on behalf of Lady Pemberton: 'Her Ladyship requires your Chelsea property for a 2-week stay. She will arrive with two personal staff. No photographs of the interior are to be taken during her stay. Full rate expected.'",options:[
      {text:"Verify the booking details, update your house rules to reflect her requirements, brief your cleaner on discretion protocols",pts:200,good:true,reaction:"The stay goes immaculately. Lady Pemberton sends a handwritten thank-you note. The PA calls to book quarterly. Your property enters a very exclusive referral network."},
      {text:"Ask for double the rate given the unusual requirements",pts:120,good:true,reaction:"The PA agrees immediately. 'Of course.' You just discovered that high-value guests often have significant flex on rate. An important lesson."},
      {text:"Decline — it all sounds very complicated",pts:-60,good:false,reaction:"Understandable caution, but this was a low-complication, high-value booking. The requirements were straightforward. £3,800 in revenue declined."},
      {text:"Accept, then mention it to a friend ('you'll never guess who just booked my place')",pts:-300,good:false,reaction:"Lady Pemberton's PA hears about it. Booking cancelled. Legal letter received. Your name is circulated in HNWI circles as untrustworthy. Career-altering mistake."},
    ],tip:"Discretion is a premium product. High-value guests pay significantly more for confidentiality — and they test it, always."},
    {guest:"The Startup Team",mood:"hustle mode 💻",icon:"💻",drama:false,scenario:"A tech startup wants to use your Chelsea townhouse as their 'strategy offsite' for 4 days — 8 people working, 6 sleeping. They need fast WiFi, extra chairs, and flexible checkout.",options:[
      {text:"Provide a detailed 'work-from-home kit' (extra chairs, power strips, router upgrade), charge a small supplement, accommodate flexibly",pts:170,good:true,reaction:"The team is blown away. CEO books you for the next two quarterly offsites. Word spreads in London's startup scene. You become the go-to offsite venue."},
      {text:"Tell them the max occupancy is 6 — 8 working guests isn't acceptable",pts:-80,good:false,reaction:"The 8 people weren't sleeping — just working during the day. You've misread the booking and lost a high-value repeat client."},
      {text:"Accept without any modifications — they'll figure it out",pts:40,good:true,reaction:"They manage with extension leads they bring themselves. A bit chaotic. 3 stars. 'Great space but not set up for work.'"},
      {text:"Charge them double the rate for 'commercial use'",pts:-60,good:false,reaction:"They cancel and book a WeWork meeting room instead. You've turned a 4-day high-rate booking into zero revenue."},
    ],tip:"The 'work from anywhere' trend has created huge demand for well-equipped residential spaces. A £50 investment in power strips and good WiFi can unlock a premium market."},
  ],
  4: [
    {guest:"A-List Guest",mood:"private 🕶️",icon:"🕶️",drama:true,scenario:"A talent agency calls: their client — a globally recognised musician — wants to rent your Mayfair penthouse for 3 weeks. NDAs required for you, your cleaner, and your managing agent. No social media. Full rate plus 20% privacy premium.",options:[
      {text:"Agree entirely — brief all staff on the NDA, arrange discrete key handover, ensure no contact beyond what's requested",pts:280,good:true,reaction:"Three flawless weeks. The agency sends a bottle of vintage Château Pétrus as a thank you. Two referrals follow within the month. You're now on a very exclusive approved list."},
      {text:"Post a cryptic Instagram story with the view from your penthouse — just the view, nothing identifying",pts:-400,good:false,reaction:"The agency's security team identifies the view within hours. NDA breach claimed. Legal proceedings initiated. Airbnb account terminated. Career over."},
      {text:"Agree but charge 40% privacy premium instead of 20%",pts:140,good:true,reaction:"The agency accepts without hesitation. You've just discovered that elite discretion is worth more than you thought. A formative lesson in premium pricing."},
      {text:"Say yes but ask if you can take one photo for your property portfolio",pts:-200,good:false,reaction:"Booking immediately cancelled. 'We require absolute discretion' was not ambiguous. The agency blacklists you."},
    ],tip:"In the HNWI market, discretion isn't a courtesy — it's a deliverable. Treat it with the same seriousness as any other contractual obligation."},
    {guest:"Mr & Mrs Chen",mood:"outraged 😡",icon:"😡",drama:true,scenario:"The Chens check in and find a small camera hidden in a smoke detector above the bed — left by the previous owner. They call you absolutely furious, recording the call.",options:[
      {text:"Apologise without qualification, offer an immediate full refund, arrange alternative accommodation at your cost, contact Airbnb proactively to report it before they do",pts:200,good:true,reaction:"Airbnb notes your proactive reporting. The previous owner is prosecuted. Your account receives a rare commendation for responsible hosting. The Chens are satisfied with your response."},
      {text:"Deny any knowledge and dispute their claim — there was no camera when you took over",pts:-500,good:false,reaction:"The Chens have video evidence. You have no credibility. Airbnb removes your listing permanently. Police investigation opened. Do not pass go."},
      {text:"Offer them the rest of their stay free in exchange for not reporting it",pts:-400,good:false,reaction:"Attempting to suppress a hidden camera report is a criminal offence. Airbnb bans you. Police are informed anyway."},
      {text:"Explain you inherited the property and had no knowledge — investigate immediately and remove it in front of them",pts:160,good:true,reaction:"Credible, accountable response. Refund offered. Chens accept. You conduct a full property sweep professionally and document it. Trust partially recovered."},
    ],tip:"Always conduct a full sweep of any inherited or newly acquired property before taking your first booking. Every room. Every device."},
    {guest:"Three recent guests",mood:"satisfied 😊",icon:"😊",drama:false,scenario:"Your Mayfair penthouse has received three consecutive 4.6-star reviews. Beautiful comments — but 4.6, not 5. You need 4.8 to maintain Superhost. Each review mentions 'slightly slow check-in process'.",options:[
      {text:"Install a smart lock system with a digital welcome guide — eliminate all friction from arrival",pts:200,good:true,reaction:"Next 8 reviews average 4.95. 'Smoothest check-in I've ever experienced' appears in four consecutive reviews. Superhost status secured comfortably."},
      {text:"Email all three guests asking them to amend their reviews to 5 stars",pts:-180,good:false,reaction:"One guest reports the request. Airbnb investigates for review manipulation. Official warning issued. Superhost status suspended."},
      {text:"Accept 4.6 — it's still excellent",pts:-80,good:false,reaction:"Next review cycle: same pattern. You fall below 4.8 threshold. Superhost status lost. Visibility drops 30%. Bookings decline notably."},
      {text:"Hire a professional hospitality consultant to audit the check-in experience",pts:160,good:true,reaction:"Consultant identifies 3 friction points. All resolved in a week. Check-in score shoots up. 'Worth every penny' — you, three months later."},
    ],tip:"Superhost status increases booking conversion by 20–30%. Losing it is a significant commercial event. Protect it proactively."},
    {guest:"Alessandro G.",mood:"charming 😊",icon:"😊",drama:true,scenario:"Alessandro has been a perfect guest for 4 days. He messages: 'I hope you don't mind — I mentioned your beautiful penthouse to some friends in London and they'd love to pop by tonight for a little dinner. Maybe 8–10 people. Nothing wild, I promise.'",options:[
      {text:"Politely but absolutely decline: 'I'm sorry Alessandro, my house rules don't allow additional visitors. I hope you understand.'",pts:140,good:true,reaction:"Alessandro is completely fine about it. 'Of course, I should have checked first.' 5-star review praising your professionalism. No incident."},
      {text:"Say yes — Alessandro has been lovely and it sounds like a proper dinner",pts:-250,good:false,reaction:"'8–10 people' becomes 35 by 10 PM. £2,800 in damage. Neighbours call the council. Your short-let licence comes under formal review."},
      {text:"Say yes but ask for a £500 event deposit first",pts:100,good:true,reaction:"Alessandro pays the deposit. Dinner is genuinely lovely — 8 people, beautifully behaved. Deposit returned. 5-star review."},
      {text:"Ignore the message and assume he won't do anything without a reply",pts:-160,good:false,reaction:"Alessandro interprets silence as consent. The dinner happens. You had no formal record of refusing. Your position in any Airbnb dispute is severely weakened."},
    ],tip:"Never ignore a request for something you'd refuse. Silence can be interpreted as consent. Always respond clearly and document your position."},
    {guest:"The Nakamura-Williams Group",mood:"expecting excellence 💎",icon:"💎",drama:false,scenario:"Your property manager resigns via text on a Wednesday with 10 days' notice. You have 6 bookings in the next 3 weeks including a Fortune 500 corporate party arriving on Friday.",options:[
      {text:"Engage a premium property management agency immediately as interim cover — cost is secondary to continuity",pts:200,good:true,reaction:"Agency steps in Thursday morning. All 6 bookings handled seamlessly. Guests notice nothing. Fortune 500 client re-books for Q2. You've bought time to find the right permanent replacement."},
      {text:"Attempt to manage all 6 bookings yourself remotely",pts:-150,good:false,reaction:"You miss a check-in call at 9 PM on Friday. The Fortune 500 guests are left outside for 40 minutes. They escalate to their travel manager who contacts Airbnb. 2-star group review."},
      {text:"Close the listing and cancel all 6 bookings",pts:-400,good:false,reaction:"6 cancellations. Maximum Airbnb penalties applied. Superhost status permanently revoked. £11,000 in revenue lost. The Fortune 500 client's travel manager circulates a warning in their network."},
      {text:"Ask the resigning manager to recommend and brief their replacement",pts:160,good:true,reaction:"Their friend takes over with 2 days of handover. Reasonable transition. All bookings covered. You formalise the recruitment properly from a position of stability."},
    ],tip:"At the Mayfair level, your property manager is a critical single point of failure. Always have an emergency contact at a professional agency on speed dial."},
    {guest:"Baron von Steinberg",mood:"eccentric 🧐",icon:"🧐",drama:true,scenario:"An Austrian baron has booked your penthouse for 10 nights. On day 3 he calls: 'The paintings are all wrong. I require them removed and replaced with my own collection — which will arrive tomorrow by private courier. Also, the grand piano must be tuned. Today.'",options:[
      {text:"Remove your paintings carefully (photographing their condition), arrange a piano tuner for that afternoon, accommodate graciously",pts:180,good:true,reaction:"The baron is delighted. His own paintings are extraordinary. He has the piano tuner back twice. He leaves your paintings in better condition than he found them — and a £500 tip for your housekeeper. 5 stars."},
      {text:"Decline both requests — your property, your paintings, your piano",pts:-60,good:false,reaction:"The baron checks out after 4 days. 'Host unwilling to accommodate reasonable requests.' 2-star review. You refund 6 nights."},
      {text:"Agree to the paintings but not the piano tuning",pts:80,good:true,reaction:"Compromise accepted. Piano tuning request was eccentric but harmless. Missed an opportunity for a perfect stay, but no real damage done."},
      {text:"Charge £200 for the painting removal service and £150 for piano tuning coordination",pts:140,good:true,reaction:"The baron finds this entirely reasonable. 'Of course.' He pays immediately without discussion. You've just learned that HNWI guests expect — and respect — premium service charges."},
    ],tip:"Ultra-high-net-worth guests often make unusual requests that are entirely reasonable to fulfil. Accommodate first, charge appropriately, delight always."},
  ],
  5: [
    {guest:"Royal advance team",mood:"formal 👑",icon:"👑",drama:true,scenario:"A private secretary calls: 'On behalf of a member of the Royal Family, we would like to enquire about a 3-week residence with 8 staff, full discretion protocols, and advance security sweeps of the property. Can you accommodate?'",options:[
      {text:"Request a formal briefing document, engage your solicitor, clear your insurance for the period, accommodate with full professional protocol",pts:400,good:true,reaction:"The residence goes flawlessly. A handwritten letter of thanks arrives. Your property is placed on a permanent list of approved residences. A quiet but extraordinary credential."},
      {text:"Mention it to a journalist friend as an 'off the record' conversation",pts:-600,good:false,reaction:"It gets published. Security breach. Legal action from multiple directions. Your name is permanently associated with a breach of royal security. Criminal investigation opened."},
      {text:"Charge 5× your standard rate",pts:200,good:true,reaction:"Accepted without hesitation. 'Of course.' You've just learned something important about your own pricing relative to this market."},
      {text:"Decline — the complexity feels overwhelming",pts:-80,good:false,reaction:"Understandable but unnecessary. The advance team does all the complex work. Your role is to facilitate. £45,000 in revenue declined."},
    ],tip:"At the mansion level, your guests sometimes have more security staff than you have upgrades. Engage professional support and stay in your lane."},
    {guest:"Lumière Productions",mood:"creative 🎬",icon:"🎬",drama:true,scenario:"A BAFTA-winning director wants to film a period drama in your mansion for 12 days. The location fee is £78,000. They need all furniture covered or removed, will install their own lighting grid, and require 24/7 access.",options:[
      {text:"Hire a specialist entertainment lawyer, negotiate a full location agreement with a £15,000 damage bond, take out a supplemental policy",pts:450,good:true,reaction:"The shoot runs perfectly. Your mansion appears in the film's key promotional materials. Bookings spike 60% after the trailer drops. The director's production company becomes a recurring client."},
      {text:"Accept via email with a standard rental agreement",pts:-300,good:false,reaction:"The lighting grid damages a Grade II listed ceiling cornice. Repair cost: £31,000. No specialist bond. You're liable. Net result: £47,000 profit turned into financial catastrophe."},
      {text:"Decline — too disruptive to the property",pts:-50,good:false,reaction:"Reasonable caution, but with the right legal framework this was a transformational revenue opportunity. £78,000 and national exposure declined."},
      {text:"Negotiate 20% upfront, 80% on completion, with a £20,000 bond",pts:300,good:true,reaction:"Strong commercial terms. Production agrees. All risk well-covered. £78,000 received. Property returned in perfect condition."},
    ],tip:"Film location fees for Grade II listed properties can reach £5,000–£10,000 per day. Always use an entertainment lawyer, not a generic solicitor."},
    {guest:"500k Followers",mood:"overwhelming 🌊",icon:"🌊",drama:false,scenario:"A luxury travel blogger posts a photo from your mansion (taken during their stay with permission). It goes viral overnight — 2.3 million impressions. Your inbox has 340 booking enquiries in 14 hours. Airbnb can't process them fast enough.",options:[
      {text:"Pause the listing immediately, take 48 hours to review all enquiries carefully, select only fully-verified high-value guests, then reopen at a 35% rate increase",pts:300,good:true,reaction:"You select 6 premium bookings worth £62,000. Quality guests. Outstanding reviews. Your new rate holds. The viral moment becomes a permanent step-change in your property's market position."},
      {text:"Accept as many bookings as possible while the momentum lasts",pts:-250,good:false,reaction:"Operations collapse. Double bookings. Overwhelmed cleaner quits. Three guests arrive to problems. Rating drops from 4.9 to 4.2 in one week."},
      {text:"Raise rates 3× immediately",pts:200,good:true,reaction:"Demand absorbs it completely. You receive 180 enquiries at the new rate. Self-selecting premium clients book immediately. Conversion is outstanding."},
      {text:"Do nothing — just let the bookings flow in normally",pts:-100,good:false,reaction:"Unvetted guests flood in. One group hosts an unauthorised event. Rating takes a hit. The viral moment becomes a headache rather than a breakthrough."},
    ],tip:"Viral moments are gifts — but only if your operations can absorb the volume. Pause, curate, price up, then reopen. Never let momentum override due diligence."},
    {guest:"The Ashworths",mood:"guilty 😓",icon:"😓",drama:true,scenario:"The Ashworth family call you the morning of checkout: 'Something terrible has happened. We were moving the dining table and the antique chandelier — the one you mentioned was irreplaceable — has come down. It's in pieces. We are devastated and fully prepared to take responsibility.'",options:[
      {text:"Stay calm, document everything by photo and video, contact your specialist contents insurer immediately, get an independent valuation, pursue through proper channels",pts:300,good:true,reaction:"Insurance covers £48,000 replacement. The Ashworths contribute via Airbnb's AirCover. Professional resolution. The Ashworths, despite causing the damage, leave a 4-star review praising your grace under pressure."},
      {text:"Accept their sincere apology and let it go — accidents happen",pts:-350,good:false,reaction:"£48,000 chandelier. Gone. Your insurer notes you failed to report the incident within the required 24-hour window. Future claims affected. A catastrophic act of kindness."},
      {text:"Demand immediate cash payment of £50,000 before they leave",pts:-120,good:false,reaction:"The Ashworths' solicitor arrives within the hour. You've created a legal dispute where an insurance claim would have sufficed. 6-month resolution process."},
      {text:"Engage your solicitor, document everything, pursue via Airbnb AirCover and your insurance simultaneously",pts:250,good:true,reaction:"Belt and braces approach. Full recovery within 6 weeks. Solicitor's fee is covered by AirCover. Thorough and professional."},
    ],tip:"At the mansion level, standard Airbnb AirCover is wholly insufficient. Specialist high-value contents and liability insurance is non-negotiable."},
    {guest:"Sotheby's client",mood:"discreet 🎨",icon:"🎨",drama:true,scenario:"A Sotheby's broker calls: an UHNWI collector wants to store and display 7 works valued at £12M in your mansion for 10 days during the Frieze London sale. They will pay £25,000. They need your answer in 4 hours.",options:[
      {text:"Arrange specialist fine art insurance for the period, engage a security firm, verify climate control specifications, then confirm",pts:380,good:true,reaction:"The collection is displayed. Sotheby's refer three further UHNWI clients. You've entered a new market entirely. A single phone call changed the trajectory of your hosting career."},
      {text:"Say yes and hope the mansion's conditions are sufficient",pts:-350,good:false,reaction:"Humidity fluctuation damages two works. Combined value: £3.2M. You are personally liable. Criminal proceedings opened for negligence. Career-ending."},
      {text:"Decline professionally — this is outside your current capabilities",pts:80,good:true,reaction:"Sotheby's broker respects the candour. 'We appreciate the honesty.' They keep you on their list for future — more straightforward — bookings."},
      {text:"Ask for 48 hours to arrange proper coverage",pts:280,good:true,reaction:"Sotheby's grants the extension. You arrange everything properly. The collection arrives safely. Professional execution recognised."},
    ],tip:"Opportunities at this level require capabilities at this level. Know what you can and cannot safely facilitate — and build the infrastructure before you need it."},
    {guest:"The Grand Prix Party",mood:"celebratory 🏁",icon:"🏁",drama:true,scenario:"A group of F1 team principals have booked your mansion for the British Grand Prix weekend. On Saturday evening, with 2 days remaining, you discover via a neighbour that they've erected a hospitality marquee in your walled garden without permission, hosting 80 people.",options:[
      {text:"Attend immediately, remain calm, explain the marquee requires planning permission and must come down, offer a compromise (30 guests maximum, no marquee)",pts:280,good:true,reaction:"They comply with remarkable good humour. 'Fair enough, we should have asked.' The 30-person garden event is legendary. Your property gets namechecked in a paddock podcast. Remarkable client."},
      {text:"Call the police and let them deal with it",pts:100,good:true,reaction:"Police arrive. Marquee comes down. Guests are unhappy but compliant. 2-star review: 'Host overreacted.' Though your property and licence are protected. A defensible call."},
      {text:"Say nothing — they're leaving in 2 days and they're F1 team principals",pts:-300,good:false,reaction:"A council enforcement officer visits. The marquee requires planning permission. Your property is issued a formal enforcement notice. The short-let licence review process begins."},
      {text:"Charge them a £5,000 retrospective event fee and document it on Airbnb",pts:180,good:true,reaction:"They pay without argument. '£5k? Cheap for what we've had here.' You've maintained commercial leverage. Smart recovery from a difficult situation."},
    ],tip:"Unauthorised structures on your property — even temporary ones — can trigger planning enforcement. Always have pre-approved event terms in your welcome guide."},
  ],
};
// ─── CLUELESS GUEST SCENARIOS ─────────────────────────────────────────────────
// Injected into ALL_QUESTIONS at the end of each property's array.
// These are lighthearted, funny situations — the kind every host actually
// deals with far more often than the dramatic ones.
(function injectCluelessScenarios() {
  const funny = {
    1: [
      {guest:"Gary & Linda",mood:"baffled 😵",icon:"😵",drama:false,damage:"confused_tech",scenario:"Gary calls at 9:15 PM. 'Hi, sorry to bother you. We can't find the telly remote. We've looked everywhere. We moved all the cushions. Linda checked under the bed. We're missing the football.' A pause. 'Also, is the telly broken? The screen is black.'",options:[
        {text:"Ask if they've pressed the button on the side of the TV itself — it's a smart TV that turns on without the remote",pts:110,good:true,reaction:"'...Oh. Oh it's come on. Linda! LINDA IT'S ON. Brilliant, cheers mate. Sorry for the bother.' 5 stars. 'Host incredibly helpful and patient.' You smile for the rest of the evening."},
        {text:"Drive over to investigate — this could be a real fault",pts:50,good:true,reaction:"You arrive to find Gary holding the TV remote upside down. You show him the buttons. He buys you a beer. You leave laughing. 5 stars: 'Host came over personally at 9 PM. Incredible service.'"},
        {text:"Send detailed written instructions with a diagram",pts:80,good:true,reaction:"Gary messages back 4 minutes later: 'Found it! It was behind the plant. Cheers.' 5 stars. 'Very clear instructions.' The remote was never missing — it was hidden by Linda."},
        {text:"Tell him to use the smart TV buttons on the side panel and leave it at that",pts:60,good:true,reaction:"A longer silence, then: 'Found it ta.' 4 stars. 'Perfectly fine stay.' You will never know what happened with the remote."},
      ],tip:"Keep a laminated 'how to use the flat' card on the coffee table. A £3 lamination job eliminates 40% of guest calls."},

      {guest:"Deborah",mood:"flustered 😳",icon:"😳",drama:false,damage:"confused_tech",scenario:"Deborah messages at 11 PM: 'Hi! The bedroom is letting in a lot of light from the street — the orange light is shining right on my face. I've tried pushing the curtains together but there's a gap. Also I noticed there's a cord hanging down on the side of the window. Is that supposed to be there or is something broken?'",options:[
        {text:"Message back warmly: 'That cord IS the blind — give it a gentle pull and it should roll down fully! The gap in the curtains is fixed by the hook on the left-hand side.'",pts:120,good:true,reaction:"'OH MY GOD. I thought it was a broken pull cord for a light fitting. It works perfectly. I'm so sorry!! I feel ridiculous.' 5 stars. She refers two colleagues who both book. 'The host explains everything perfectly.'"},
        {text:"Call her to walk her through it — faster than texting",pts:100,good:true,reaction:"She answers on the first ring. You explain, she pulls the cord, lets out a shriek of delight. 'I was sleeping in the orange glow for NO REASON.' Instant 5 stars and a very funny review."},
        {text:"Send photos of the blind mechanism with numbered steps",pts:110,good:true,reaction:"She messages back a photo of the blackout darkness with a thumbs up emoji. 5 stars. 'Host provided extremely clear visual instructions. Top marks.' Job done."},
        {text:"Apologise and offer to pop a sleep mask in the welcome pack for future guests",pts:30,good:true,reaction:"Deborah sleeps with the light on and gives 3 stars: 'Room very bright. Host apologetic.' The blind was working the whole time. Missed opportunity."},
      ],tip:"Add a single line in your check-in instructions for anything non-obvious: 'The cord on the right side of the bedroom window operates the blackout blind.' Saves 11 PM messages every time."},
    ],

    2: [
      {guest:"Kevin",mood:"stressed 😰",icon:"😰",drama:false,damage:"confused_tech",scenario:"Kevin calls sounding mildly panicked: 'Hi yeah, I've been trying to connect to the WiFi for 45 minutes. I'm entering the password but it keeps saying incorrect. I've got a deadline in an hour. The password in the welcome book is — I'm reading this right — 'ShORedItCH2024!' with a capital S, lowercase h, uppercase O...' He reads all 14 characters back to you. Every single one is correct.",options:[
        {text:"Ask if the WiFi symbol shows 5 bars on the router — then ask Kevin to forget the network and reconnect fresh",pts:130,good:true,reaction:"'Oh. It was already connected. To the wrong network — the neighbour's. Same name, different password.' Laptop connected in seconds. Kevin smashes his deadline. 5 stars: 'Absolute hero of a host.'"},
        {text:"Tell him to restart his laptop AND the router, then try again",pts:110,good:true,reaction:"Router restart clears a firmware glitch. Kevin's in within 90 seconds. 'I could have done that myself couldn't I.' 5 stars. 'Fast, effective, no judgment.'"},
        {text:"Offer to come over and look at the router personally",pts:70,good:true,reaction:"You arrive to find Kevin's laptop had its WiFi toggled off by accident. You press one key. Kevin stares at the screen. 'I owe you a pint.' 5 stars and mild personal embarrassment for Kevin."},
        {text:"Email him a PDF troubleshooting guide",pts:-60,good:false,reaction:"Kevin can't open the PDF because he has no internet. You both realise this at the same time. 2 stars: 'Sent me a PDF. Unhelpful.'"},
      ],tip:"Stick a laminated WiFi card next to the router showing the network name highlighted. 'Connect to THIS one.' Half of all WiFi issues are guests connecting to the neighbour's network."},

      {guest:"Steph & Tom",mood:"confused 😕",icon:"😕",drama:false,damage:"confused_tech",scenario:"Steph messages at 8 AM: 'Morning! We want to have a shower but we can't figure out how the controls work. There are two round knobs and a button. We've turned both knobs and pressed the button but either nothing happens or it sprays freezing cold water sideways from something near our feet. We're a bit scared of it now.'",options:[
        {text:"Message immediately: 'Left knob = temperature, right knob = pressure, the lower spray is the bath filler tap — push it DOWN to send water up to the shower head!'",pts:130,good:true,reaction:"'THAT'S WHAT THAT DOES. Tom got completely soaked trying to figure this out at 7 AM. We're crying laughing.' 5 stars and the funniest review you'll ever receive."},
        {text:"Record a 30-second voice note walking them through it step by step",pts:120,good:true,reaction:"Tom listens to it in the bathroom. 'Oh my god it's that simple.' They shower, laugh, rate you 5 stars. 'Host does brilliant audio tutorials for confused shower users.'"},
        {text:"Add a laminated shower instruction card to the bathroom — send them a photo of what it will say",pts:100,good:true,reaction:"'We'll look out for it next time we stay! (And we will be back.)' 5 stars. The instruction card saves every future guest. Best £2 you ever spent."},
        {text:"Apologise and say the shower is admittedly a bit confusing",pts:-40,good:false,reaction:"Steph has a cold shower. Tom avoids it entirely. 3 stars: 'Shower baffling and host not helpful.' The shower was not confusing. You just didn't explain it."},
      ],tip:"Non-obvious appliances — power showers, induction hobs, smart locks, composting bins — all need a laminated instruction card. What's obvious to you is a mystery to a first-time visitor."},
    ],

    3: [
      {guest:"Nigel",mood:"exasperated 🙄",icon:"🙄",drama:false,damage:"confused_tech",scenario:"Nigel calls on day two: 'Hello. The heating. I've pressed the round thermostat thing in the hall and it makes a clicking sound but nothing seems to be happening and the flat is absolutely freezing. Also I don't know if this is related but I've turned it up to 30 degrees and the display says it's on but I genuinely cannot feel any heat whatsoever.' It is mid-April. The boiler has a summer/winter switch.",options:[
        {text:"Ask if there's a small switch on the side of the boiler itself marked with a snowflake and a sun — flip it to the sun",pts:140,good:true,reaction:"'...There is. It's been on the snowflake the whole time, hasn't it. Right. Thank you.' Heat comes on instantly. Nigel warms up, thaws emotionally, leaves 5 stars and 'extremely responsive host' in the review."},
        {text:"Pop round and switch it yourself — it's a 2-minute job",pts:110,good:true,reaction:"You arrive, flip the switch, the radiators click on. Nigel stares at you. 'I'm a solicitor. I own four properties. I have never felt so humbled.' 5 stars. Glorious."},
        {text:"Explain the summer/winter switch in a WhatsApp voice note with a photo",pts:120,good:true,reaction:"Nigel finds the switch, flips it, messages back: 'First class service. All warm now. Apologies for the alarm.' 5 stars. One of your better Monday afternoons."},
        {text:"Arrange for a heating engineer to call out just in case",pts:30,good:true,reaction:"Engineer turns up, sees the switch in summer mode, flips it, charges £95 call-out fee. Nigel is warm but you're £95 lighter. Not wrong, but very expensive for a boiler switch."},
      ],tip:"Add a boiler instruction page to your welcome guide with a photo of the summer/winter switch. It costs nothing and saves a call-out fee every single spring and autumn."},

      {guest:"The Wentworths",mood:"sheepish 🐑",icon:"😶",drama:false,damage:"confused_tech",scenario:"Mrs Wentworth calls on their third morning: 'We're so sorry to bother you, I know this sounds silly. We've been making tea on the hob in a saucepan for two days because we couldn't find the kettle. My husband says it must be in a cupboard but we've checked all of them. Is there actually a kettle?' There is a kettle. It is on the counter. It has been there the entire time.",options:[
        {text:"Ask warmly if they've had a look at the appliance on the left of the counter next to the toaster — the tall silver thing with a handle",pts:140,good:true,reaction:"A very long pause. 'Oh. Oh my goodness. We thought that was a... water filter of some kind.' Three days of hob tea. Two adults. 5 stars and the single funniest review you'll ever read."},
        {text:"Send a photo of the kitchen annotated with arrows",pts:130,good:true,reaction:"Mrs Wentworth replies immediately: 'I'm choosing not to say where we thought that was. Thank you.' 5 stars. 'Brilliant host. Very kind about our spatial awareness difficulties.'"},
        {text:"Ask cheerfully: 'Have you tried the tall silver device on the counter next to the toaster?'",pts:130,good:true,reaction:"A pause so long you wonder if the call dropped. '...That's the kettle.' Yes, Mrs Wentworth. That is the kettle. 5 stars: 'Host endlessly patient and never made us feel foolish.'"},
        {text:"Tell them you'll add clearer labels to the kitchen appliances before their next visit",pts:50,good:true,reaction:"The Wentworths spend the rest of the trip making boiled-water tea from the saucepan out of stubbornness and dignity. 4 stars. 'Very comfortable stay.' Perfectly fine outcome."},
      ],tip:"A simple welcome guide with a labelled kitchen photo is worth its weight in gold. 'The kettle, toaster, and coffee machine are on the left counter.' Never assume."},
    ],

    4: [
      {guest:"Investment Banker Mike",mood:"baffled 😵",icon:"😵",drama:false,damage:"confused_tech",scenario:"Mike calls from Mayfair at 6 PM. He manages a £2.4 billion portfolio. He has two assistants. He cannot turn on the lights. 'I've pressed every switch in the entrance hall. Some of them seem to do nothing. One of them made a clicking sound from somewhere upstairs. I've checked the fuse box — all the switches are up. The flat just seems to... not have lights.'",options:[
        {text:"Ask if he's noticed the small black square touchpads on the wall — the smart lighting system activates with a press-and-hold, not a flick",pts:140,good:true,reaction:"'Press and hold. Right. It... it's working. The whole flat has just lit up.' A man who manages £2.4 billion needed you to explain light switches. He leaves a 5-star review and a £200 tip via bank transfer."},
        {text:"Have your property manager call round to give Mike a full smart home walkthrough",pts:120,good:true,reaction:"Property manager spends 8 minutes on a guided tour. Mike is genuinely impressed and books your property for the next 4 months. 5 stars. 'Property manager outstanding.'"},
        {text:"Send a video walkthrough of the smart home panel from your phone",pts:130,good:true,reaction:"Mike watches it once and has the flat fully operational in 3 minutes. 5 stars: 'Comprehensive video tutorial for an admittedly complex system. Impressive setup.'"},
        {text:"Apologise for the complexity and offer to simplify the system for future guests",pts:30,good:true,reaction:"Mike sits in candlelight with his phone torch on for the evening rather than admit he still can't do it. 3 stars. 'Lighting system needlessly complicated.' A rare failure of a brilliant amenity."},
      ],tip:"Smart home systems need a one-page visual guide at every guest's eye level. 'Press and hold = on. Double tap = off. The panel by the door controls the whole flat.'"},

      {guest:"Clara",mood:"embarrassed 😳",icon:"😳",drama:false,damage:"confused_tech",scenario:"Clara sends a message at 10:30 PM: 'Hi, I hope you don't mind me asking this. This is quite embarrassing. I've been trying to close the electric blinds in the bedroom for about 20 minutes. I've tried pressing all the buttons on the remote. Some of them make the blinds go up a bit and then stop. I've now accidentally made the blind in the living room fully close and I can't open it again. I'm very sorry.'",options:[
        {text:"Message immediately: 'No need to apologise at all! Button 1 opens, button 3 closes, button 2 is the stop. Each blind is on its own channel — press CH first, then select 1, 2 or 3.'",pts:140,good:true,reaction:"Clara un-jams the living room blind, closes the bedroom blind perfectly, messages you three exclamation marks and a sunflower emoji. 5 stars: 'Host explained the blinds at 10:30 PM without a hint of judgment. A saint.'"},
        {text:"Call her and walk through it together in real time",pts:130,good:true,reaction:"You talk her through it in 90 seconds. 'They should really put this in the instructions.' You agree. You add it to the welcome guide before midnight. 5 stars."},
        {text:"Send a photo of the remote with the buttons numbered and labelled",pts:130,good:true,reaction:"Clara has everything working in under 2 minutes. 'This should genuinely be in the welcome pack.' It now is. 5 stars: 'Improved the instructions based on my feedback in real time. Remarkable host.'"},
        {text:"Reassure her that the blind positions auto-reset overnight and not to worry",pts:-80,good:false,reaction:"They do not auto-reset. Clara sleeps with the living room blind fully down in a 4th-floor Mayfair flat. She can't see the Hyde Park view she specifically paid extra for. 2 stars: 'Blinds stuck closed the whole time.'"},
      ],tip:"Motorised blind remotes need a laminated card next to every remote: 'CH = which blind. 1 = open. 3 = close. 2 = stop.' Without it, guests will fight those remotes for hours."},
    ],

    5: [
      {guest:"Lord and Lady Pemberton",mood:"flustered 😳",icon:"😳",drama:false,damage:"confused_tech",scenario:"Lady Pemberton calls at 7:45 AM. 'Good morning. I do apologise for disturbing you at this hour. Rupert and I have been attempting to make tea for some time. The Aga appears to be off. We've pressed the large buttons along the front panel. One of them made a whistling sound. We're not in distress but we are rather in need of tea.'",options:[
        {text:"Explain that the Aga is always-on but has four zones — the right hot plate cover needs to be lifted, not the left — and the kettle sits on the right",pts:150,good:true,reaction:"'Oh. OH. We've been pressing the hot plate lids, not lifting them. Rupert has been crouching in front of it for twenty minutes. Good heavens.' Full English shortly after. 5 stars. A story that gets told at dinner parties for years."},
        {text:"Have your housekeeper pop round with tea, croissants, and a printed Aga instruction sheet",pts:130,good:true,reaction:"Lady Pemberton is so delighted by the croissants she barely mentions the Aga confusion. Lord Pemberton frames the instruction sheet as 'a charming piece of domestic history'. 5 stars and a handwritten thank-you note."},
        {text:"Offer a gentle walk-through by phone: 'The right lid lifts — there's a slight resistance — and the surface underneath is your hotplate.'",pts:140,good:true,reaction:"A delighted gasp from the kitchen. 'Rupert. RUPERT. It was the lid.' Tea made. Crisis resolved. 5 stars. A review that opens with 'Having never operated an Aga in our lives...'"},
        {text:"Apologise and say there's a coffee machine on the kitchen island if the Aga is proving difficult",pts:40,good:true,reaction:"Lord Pemberton is a coffee machine man at heart but feels it is important to conquer the Aga on principle. He spends another 25 minutes on it. They eventually have Nespresso. 3 stars and a complicated paragraph about authenticity."},
      ],tip:"Aga cookers, wine coolers, integrated appliances, and complex hobs all need dedicated instruction cards. What's intuitive after ten years is completely opaque on day one."},

      {guest:"The Kowalskis",mood:"baffled 😵",icon:"😵",drama:false,damage:"confused_tech",scenario:"Piotr messages at 9 PM: 'Hello! Quick question. We are trying to use the roof terrace but the door will not open. We have pushed and pulled and turned the handle many times. We looked for a key but there was not one in the welcome pack. We thought maybe the terrace is not included in our booking? But it says on the listing it is.' The terrace is included. The door opens inward.",options:[
        {text:"Message back with a laugh emoji: 'The terrace door opens inward — give it a firm push toward you while turning the handle. The hinges are on the outside so it looks like it should pull!'",pts:140,good:true,reaction:"Three minutes later: a photo of the Kowalski family on the terrace with the London skyline behind them, all grinning, thumbs up. 5 stars: 'The terrace is extraordinary. Host was brilliant about the door situation.'"},
        {text:"Send a 15-second video of you demonstrating the correct motion on a similar door",pts:130,good:true,reaction:"Piotr watches it, pushes, and is on the terrace in moments. 5 stars. A photo of the view at sunset. 'Worth every penny. Host explains everything perfectly.'"},
        {text:"Call him and describe the motion: 'Handle down, push firmly TOWARD you, don't pull — the frame swells slightly in warm weather'",pts:130,good:true,reaction:"'AH. Toward. We were pulling. We pulled for so long.' 5 stars. Family photos on the terrace. You add 'the terrace door opens inward' to the welcome guide."},
        {text:"Apologise and say you'll get the door mechanism checked by a carpenter",pts:-50,good:false,reaction:"The Kowalskis spend the rest of their stay looking at the locked terrace door, not realising they just needed to push. 2 stars: 'Promised terrace was inaccessible. Very disappointed.' A tragedy of directions."},
      ],tip:"Unusual door mechanisms — inward-opening French doors, lift-and-push patio locks, key-turning directions — are a constant source of guest confusion. A sticky arrow on the door frame solves it permanently."},
    ],

    6: [
      {guest:"Senator Whitfield",mood:"baffled 😵",icon:"😵",drama:false,damage:"confused_tech",scenario:"The Senator's aide calls at 11 PM. 'I'm sorry to call so late. The Senator would like to watch some television before bed. We've located what appears to be six remote controls on the coffee table. We have pressed buttons on all six of them. The screen remains black. One of the remotes appears to have opened the wine cooler. We are not sure how. The Senator is tired and would simply like to watch CNN.'",options:[
        {text:"Laugh internally, then calmly explain: Remote 1 (silver, longest) powers the screen. Remote 3 (black, square) controls the Apple TV. Remote 4 explains the wine cooler. CNN is on Apple TV > Live TV > CNN International.",pts:160,good:true,reaction:"The aide relays instructions. The Senator is watching CNN within 90 seconds. In the morning she asks your property manager to give her the full AV walkthrough. She books the penthouse for 6 weeks during the UN General Assembly. You label all six remotes."},
        {text:"Have a laminated AV guide created and delivered by your concierge within the hour",pts:140,good:true,reaction:"Concierge arrives at 11:30 PM with the guide, a brief walkthrough, and a cheese board. The Senator is charmed beyond reason. She refers three heads of state. You will never discuss the wine cooler incident publicly."},
        {text:"Send your building's 24-hour tech concierge up to help",pts:150,good:true,reaction:"Tech concierge presents a professional guided tour of the AV system. Senator watches CNN, falls asleep to it, and checks out saying it is 'the finest property she has ever stayed in.' 5 stars."},
        {text:"Apologise and suggest the Senator might find a good book in the library instead",pts:-100,good:false,reaction:"The aide reads this back to the Senator. The Senator stares for a moment. She books out the following morning into the Ritz. You have told a sitting US Senator to read a book. The review is brief but scorching."},
      ],tip:"Any property with more than two remotes needs a physical AV guide with photos of each remote, what it controls, and step-by-step instructions for each input source. Without it, you are one US Senator away from disaster."},
    ],
  };

  Object.entries(funny).forEach(([propId, scenarios]) => {
    const id = parseInt(propId);
    if (ALL_QUESTIONS[id]) {
      ALL_QUESTIONS[id].push(...scenarios);
    }
  });
})();
