// ─── EXTRA SCENARIOS v6 ──────────────────────────────────────────────────────
// Drawn from real-world Airbnb horror stories: trashed homes, drug parties,
// brothels, bedbugs, mould, broken boilers, broken beds, paparazzi sieges.
// Each scenario has middle-ground options with genuine tradeoffs — cheap+small,
// expensive+big, risky+variable, safe+small. The `damage` field renders an
// overlay showing the visible problem.
const EXTRA2_QUESTIONS = {
  1: [
    {guest:"Marta R.",mood:"sleepless 😩",icon:"🛏️",drama:true,damage:"broken_bed",scenario:"Marta calls in tears at 2 AM. Three nights in and the bed frame has snapped in the middle. They've slept on the floor for two nights without telling anyone. 'I've barely slept. I have a wedding in the morning. I can't function.'",options:[
      {text:"Apologise sincerely, send a £40 Uber to a 4-star hotel for the rest of her stay, fix the bed, comp the entire booking",pts:160,good:true,reaction:"She bursts into tears of relief. The wedding goes well. She leaves a 5-star review titled 'Above and beyond'. Three of her wedding guests book future stays.",damage:null},
      {text:"Ship a brand-new Hypnos divan tomorrow morning, refund 30% of the stay, deliver a hamper",pts:130,good:true,reaction:"Solid handling. New bed by lunch. 5 stars. £180 net cost but you keep the booking and earn a glowing review.",damage:null},
      {text:"Send a handyman to fix the existing frame in the morning, offer £50 off",pts:30,good:true,reaction:"Frame is screwed back together by 11 AM. She's grateful but tired. 3 stars. Handyman's bodge job will fail again in 4 months.",damage:null},
      {text:"Tell her the listing description doesn't promise 'mattress quality' and offer a £20 voucher",pts:-220,good:false,reaction:"She posts photos of the broken frame to Twitter with 14k retweets. Two news outlets pick it up. Three weeks of bookings cancel.",damage:null},
    ],tip:"Real review: a couple slept on a broken bed for 3 nights in Yerevan. The host eventually fixed it but Airbnb only offered $100 credit. Quick decisive action prevents a viral nightmare."},

    {guest:"Daniel & Priya",mood:"FURIOUS 🤬",icon:"🤬",drama:true,damage:"mould",scenario:"They send 11 photos: black mould blooms across the bathroom ceiling, behind the bed, under the kitchen sink. 'Our 4-year-old has been coughing all night. This is a category 1 hazard under the Homes Fitness Act. We're contacting the council.'",options:[
      {text:"Move them to the Shoreditch loft tonight at no extra cost, get a damp surveyor in tomorrow, full refund of Notting Hill stay",pts:170,good:true,reaction:"Surveyor identifies a leaking gutter as the source. £2,400 in remediation but no council action, no negative review, the family books Shoreditch annually for 3 years.",damage:null},
      {text:"Send a cleaner with anti-mould spray, offer 40% refund, promise a full survey next week",pts:60,good:true,reaction:"They accept reluctantly. Council still gets contacted but takes no action. 3-star review noting mould 'returned within a month'. Booking continues.",damage:null},
      {text:"Tell them mould is from their cooking/showering habits and condensation is normal in winter",pts:-340,good:false,reaction:"Council issues a Category 1 hazard notice. Listing suspended for 6 weeks. £6,000 lost revenue. National news picks up the story when she shares the medical report.",damage:null},
      {text:"Refund the stay in full and ask them to leave a private review only",pts:-80,good:false,reaction:"They take the refund, leave anyway, AND write a public review detailing the mould plus the bribery attempt. Worse outcome than just dealing with it.",damage:null},
    ],tip:"UK govt 2023: landlords must respond to mould reports urgently. Bribing for review silence is itself reportable. The cheapest path is always 'fix it properly'."},

    {guest:"Tariq M.",mood:"freezing 🥶",icon:"🥶",drama:true,damage:"freezing",scenario:"Tariq messages at 11 PM in January: 'There is no hot water and the heating won't turn on. The flat is 9°C. We have a baby. Please help.'",options:[
      {text:"Drive over now with two oil heaters and a kettle, call your boiler engineer's emergency line (£280 callout), refund the night",pts:170,good:true,reaction:"Engineer arrives by 1 AM. Boiler diagnostic: blocked condensate pipe, frozen. Fixed in 40 minutes. Tariq leaves the most heartfelt 5-star review you've ever received.",damage:null},
      {text:"Book them into the Premier Inn down the road for the night, fix boiler tomorrow",pts:120,good:true,reaction:"£140 hotel cost but family is warm in 30 minutes. Boiler engineer fixes it next day. 5 stars. Practical, fast.",damage:null},
      {text:"Send instructions on how to bleed the radiators and hope it works",pts:-140,good:false,reaction:"It doesn't. They sit in coats until 4 AM. Baby develops bronchitis. Medical letter cited in their 1-star review. Listing flagged.",damage:null},
      {text:"Offer £30 toward dinner and tell them the boiler will be looked at in the morning",pts:-180,good:false,reaction:"They check out at 3 AM and demand full refund through Airbnb. They get it. You also get a 1-star review and a 'Severe Health Risk' flag from Airbnb's safety team.",damage:null},
    ],tip:"Real Quora story: a host dismissed a 'freezing shower' complaint, claimed the guest had an 'attitude problem'. Airbnb sided with the host because there was no photographic proof — but the review was permanent."},

    {guest:"Ji-eun K.",mood:"sleepless 😴",icon:"😴",drama:false,damage:"cracked_window",scenario:"Ji-eun messages politely on day 4: 'I haven't slept properly all week. The curtains are too thin and the streetlight outside is incredibly bright. Also there's a tiny crack in the window letting cold in.' Her review will go live in 18 hours.",options:[
      {text:"Bring blackout curtains and a glazier the same day, throw in an eye mask and a £20 Pret voucher",pts:140,good:true,reaction:"Blackout curtains by 4 PM, glazier by 6 PM. She sleeps for the first time all week. 5-star review specifically praising 'the host who fixes things instantly'.",damage:null},
      {text:"Send a sleep mask and earplugs by Amazon Prime, promise blackouts before next guest",pts:80,good:true,reaction:"4-star review. 'Helpful but not perfect'. The next guest gets the curtains. Quietly clean.",damage:null},
      {text:"Comp her last 2 nights and tell her the window will be fixed shortly",pts:50,good:true,reaction:"She feels heard. 4 stars. £180 in lost revenue but no public complaint about thin curtains.",damage:null},
      {text:"Tell her thin curtains are mentioned in the listing and crack is 'cosmetic'",pts:-160,good:false,reaction:"Her review: 'Listing mentions curtains, doesn't mention being unable to sleep. Host dismissed concerns.' Three subsequent guests cite the same complaint and the review.",damage:null},
    ],tip:"Real bbqboy.net story: 2 weeks of bad sleep due to thin curtains and bright streetlight ruined an entire holiday. Sleep is the #1 review-killer."},
  ],

  2: [
    {guest:"Tom & Lex",mood:"DEVASTATED 😭",icon:"😭",drama:true,damage:"cockroach",scenario:"Day 1 photos: cockroaches in the kitchen drawer, cockroaches behind the kettle, two dead in the bath. Tom is gagging in the video. 'We're not staying. We want a full refund and an apology.'",options:[
      {text:"Refund in full immediately, send pest control today, write a sincere apology, mark the listing 'pause' for 1 week while treated",pts:150,good:true,reaction:"Pest control finds nest behind dishwasher. Two-treatment elimination, £420. They appreciate the integrity. 4-star review: 'Awful situation, host did the right thing immediately.'",damage:null},
      {text:"Refund 60%, offer them the Notting Hill flat free for one night, pest treatment next week",pts:60,good:true,reaction:"They take Notting Hill, but next guest at Shoreditch sees a roach too. Pest treatment delayed = recurring problem. 3-star review.",damage:null},
      {text:"Argue that they probably brought roaches in their luggage from the tropics",pts:-280,good:false,reaction:"They post the video to TikTok. 2.1 million views in 3 days. Listing taken offline by Airbnb. £14,000 in lost bookings. National pest control firms decline future contracts because of the publicity.",damage:null},
      {text:"Send pest control NOW, let them stay if they want, give 50% refund either way",pts:110,good:true,reaction:"They actually stay (Lex is brave). Pest control treats it that afternoon. They write a measured 4-star review. Saved a booking AND fixed the problem.",damage:null},
    ],tip:"Real Airbnb forum: a host argued cockroaches came from a guest's suitcase. The guest left a 1-star review citing the year-old previous review that said the same. Pattern + denial = guaranteed listing suspension."},

    {guest:"Marcus W.",mood:"raging 🤬",icon:"🤬",drama:true,damage:"party_chaos",scenario:"It's 3 AM. Your downstairs neighbour calls: 'There are AT LEAST 60 people in your flat. Music is shaking my ceiling. They've been arriving in groups of 20 since 11 PM. Police are on their way.' The booking is for 'Sarah, 2 guests, quiet stay'.",options:[
      {text:"Drive there now, meet police at the door, evict immediately, claim damages via Airbnb's £1m host guarantee, blacklist Sarah",pts:180,good:true,reaction:"Police clear the flat in 25 minutes. £4,800 in damage (broken door, vomit-stained sofa, cigarette burns) is fully covered. You become a Pass-The-Keys case study on rapid response.",damage:null},
      {text:"Call Sarah and demand she clears everyone out within 30 minutes, threaten £500 charge per guest over 2",pts:80,good:true,reaction:"She actually does it — partially. About 25 leave. Police arrive anyway. Damages £2,200 — partially covered. Mixed outcome but you avoided the worst.",damage:null},
      {text:"Call Airbnb support and let them handle it",pts:-160,good:false,reaction:"Airbnb takes 4 hours to reach a decision. By then the police have evicted, the flat is wrecked, neighbours have filed noise complaints, council issues a £1,000 warning notice. £8,400 damage, mostly uncovered.",damage:null},
      {text:"Do nothing — let it run its course and claim damages tomorrow",pts:-380,good:false,reaction:"The neighbour reports YOU to council for permitting an 'illegal gathering'. £4,000 fine. Three neighbours sue you for nuisance. Building's freeholder revokes short-let permission. Property earns £0 for 8 months.",damage:null},
    ],tip:"Real London host quote: 'The phone call at 3 AM saying the family checked in is not there but 60 youths are having a party is a host's worst nightmare.' Speed matters more than anything."},

    {guest:"The Henderson Family",mood:"shocked 😨",icon:"📷",drama:true,damage:"hidden_camera",scenario:"Day 2 message: 'My wife noticed the smoke detector in the bedroom has a hole that looks unusual. We've removed the cover. There appears to be a camera lens. Please explain or we are calling the police.'",options:[
      {text:"Call them immediately on speakerphone, agree it must be inspected, drive over with an electrician, agree to police involvement, offer full refund + £1,000 inconvenience payment",pts:200,good:true,reaction:"Electrician confirms it's an old vent — not a camera. Police take a statement, leave satisfied. The Hendersons appreciate the gravity with which you treated it. 5-star review: 'Took our concern seriously, came in person, made it right.' Three friends book that year.",damage:null},
      {text:"Apologise via message, refund 30%, ask them to leave the device alone for inspection tomorrow",pts:-140,good:false,reaction:"Local news picks up the story before you arrive. Even though it turns out to be an old vent, the headline is permanent: 'Family finds suspected hidden camera in London Airbnb.' Listing buried under news search results for 18 months.",damage:null},
      {text:"Defend yourself — 'There are no cameras in my listings' — and ask them to stop tampering with the device",pts:-460,good:false,reaction:"They post a video of themselves removing the cover. It goes viral. Even after it's confirmed to be an old vent, the YouTube video has 4.2 million views with the title 'Airbnb host LIES about camera'. Listing closed permanently.",damage:null},
      {text:"Offer to refund and rehouse them tonight, send an electrician later",pts:130,good:true,reaction:"They accept, you save the situation. Police are not involved because you defused it. 4 stars. The cover is replaced the same week.",damage:null},
    ],tip:"Real story (Derek Starnes, 2019): a family found a real hidden camera in a smoke detector at their Airbnb. The host was arrested for video voyeurism. Treat ALL such concerns with maximum gravity, even when innocent."},

    {guest:"Joey & Mike",mood:"DRUNK 🥴",icon:"🥴",drama:false,damage:"smoke",scenario:"3 AM video from your smart smoke alarm: thick smoke pouring from the kitchen. Joey has put a frozen pizza in the oven WITH THE PLASTIC WRAP STILL ON IT, set to 250°C, and gone to sleep. The plastic is melting onto the heating element. The fire suppression hasn't triggered yet.",options:[
      {text:"Phone them on every channel until they wake, give clear instructions: turn off oven, open windows, do NOT throw water. Engineer at 8 AM to clean the oven. Charge £350.",pts:150,good:true,reaction:"They wake up panicked, follow instructions perfectly. Engineer cleans the oven, replaces a heating element. £350 charge approved by Airbnb. They write a 4-star review thanking you for the 3 AM call.",damage:null},
      {text:"Call London Fire Brigade, evacuate the building, deal with consequences after",pts:60,good:true,reaction:"LFB arrives in 11 minutes. No fire, just smoke. They issue an automatic safety report. Building freeholder gets notified and asks pointed questions about your management. Heavy-handed but no one was hurt.",damage:null},
      {text:"Hope the smoke alarm + sprinklers handle it, deal with damage in the morning",pts:-280,good:false,reaction:"Sprinklers trigger at 4 AM. £18,000 water damage to the flat below. Insurance claim disputed because alarm was watched-and-ignored. Listing forced offline for 3 months for renovation.",damage:null},
      {text:"Drive over and handle it personally with a fire extinguisher",pts:80,good:true,reaction:"You arrive at 3:40 AM, defuse it with the extinguisher, mop up. Joey is mortified. £180 cleaning. 5-star review citing 'host literally drove across London at 3 AM'. Heroic but stressful.",damage:null},
    ],tip:"Real Bored Panda story: three Americans put plastic-wrapped pizza in the oven on max, threw water on the resulting fire, then left a 1-star review blaming the host for the oven being in Celsius. Some guests cannot be reasoned with — but you can still act."},

    {guest:"Sarah Bassini-Lite",mood:"DEVASTATED 😭",icon:"😭",drama:true,damage:"faeces",scenario:"You arrive Tuesday for changeover. The 'family of four' booking has left the flat in catastrophic condition: human faeces on the sofa and bathroom walls, used condoms scattered, chewing gum pressed into the carpet, walls smeared. They had a 60-person party. They're already gone.",options:[
      {text:"Document everything photographically, file an Airbnb damage claim within 14 days for £6,800, hire a biohazard cleaning crew, block the next 5 days of bookings",pts:170,good:true,reaction:"Airbnb pays out £5,400 (slight haircut for 'normal wear'). Biohazard crew costs £1,800. Net loss minimal. 4 future bookings rescheduled, 1 lost. The flat is fully restored within 4 days.",damage:null},
      {text:"Try to clean it yourself with a regular cleaner to save money before next guest in 6 hours",pts:-380,good:false,reaction:"Cleaner refuses on arrival, demands hazmat treatment. You scramble. Next guest arrives, smells what wasn't fully cleaned, cancels with full refund + damage claim against YOU. £4,200 lost plus 2-star review.",damage:null},
      {text:"Cancel the next 7 days, file claim for £8,500 (over-claim), threaten lawsuit",pts:-100,good:false,reaction:"Airbnb's investigation takes 11 weeks because of the over-claim. They eventually pay £4,200 (less than you'd have got). Fictitious damage claims hurt your host trust score for 2 years.",damage:null},
      {text:"File the claim, biohazard team in, but reopen bookings in 48 hours with 30% off",pts:90,good:true,reaction:"Money back via Airbnb, fast turnaround. The discount attracts a less-vetted booking who throws another smaller party. Trade-off: speed for risk.",damage:null},
    ],tip:"Real story: NYC penthouse owner Rachel Bassini found used condoms, chewing gum, and human faeces all over her flat after a guest's party. She got £30,000 via Airbnb's host guarantee BUT only because she documented everything within 14 days."},
  ],

  3: [
    {guest:"Mr Aleksandrov",mood:"smug 😏",icon:"💎",drama:true,damage:"smashed_vase",scenario:"Mr Aleksandrov's 5-year-old has knocked over the £6,000 Edmund de Waal ceramic on the hallway pedestal. It's in 47 pieces. He texts: 'It was poorly placed. Children can't be expected to avoid breakables. We're not paying for this.'",options:[
      {text:"File a £6,000 damage claim through Airbnb resolution centre with the receipt and photos, blacklist him calmly without confrontation",pts:160,good:true,reaction:"Airbnb sides with you on documented value. Aleksandrov pays £4,800 (Airbnb haircuts the rest). Polite professional review from him: 'Beautiful home, accident happened.' His insurer reimburses him.",damage:null},
      {text:"Negotiate directly: accept £2,500 cash today, no Airbnb claim, no review",pts:60,good:true,reaction:"He pays cash. Saves the time but you've lost £3,500 of value. He still leaves a review (4 stars) and tells his social circle the host 'is reasonable about damages'. Pros and cons.",damage:null},
      {text:"Let it go, write it off as a hosting cost, ask him to please be more careful",pts:-180,good:false,reaction:"He treats your courtesy as weakness, leaves a 4-star review noting the 'inconvenient layout'. His social circle now considers your flat 'walk-in damageable'. Three more breakages over next 6 months.",damage:null},
      {text:"Charge his card £6,000 immediately without permission",pts:-260,good:false,reaction:"Airbnb refunds him entirely (off-platform charges violate ToS). Account flagged. He files a chargeback. You lose the entire booking AND the vase value. 30-day suspension.",damage:null},
    ],tip:"For valuables over £500: keep dated photographs, original receipts, and an inventory document. Airbnb's resolution centre needs evidence — not stories. Documentation is the entire game."},

    {guest:"The Carlssons",mood:"weeping 😭",icon:"🛏️",drama:true,damage:"bedbugs",scenario:"Mrs Carlsson sends photos of small dark spots on the sheets and a few live insects. 'My son has 14 bites on his back. We're checking out RIGHT NOW. We want full refund and a hotel paid for the rest of our stay or we go to the council and a national newspaper.'",options:[
      {text:"Refund in full, pay for 4 nights at a 4-star hotel (£820), close listing immediately for fumigation, hire a sniffer-dog service to confirm clearance before reopening",pts:170,good:true,reaction:"Sniffer dog confirms infestation in mattress + headboard. Heat treatment £1,200. Listing closed 9 days. Carlssons' grace results in a measured 3-star review noting 'host did everything right after the issue'.",damage:null},
      {text:"Send pest controller to spray, refund 60%, offer to rehouse them at Notting Hill",pts:50,good:true,reaction:"They accept Notting Hill but feel unheard about Chelsea. Pest spray is too weak; problem returns 6 weeks later for the next booking. Worse 1-star review then.",damage:null},
      {text:"Counter that bedbugs are 'often brought by guests' and decline refund",pts:-460,good:false,reaction:"Real photos. Real bites on a child. National newspaper picks it up. Listing closed by Airbnb pending investigation. Local pest controllers won't accept your business after the publicity. £18,000 lost over 4 months.",damage:null},
      {text:"Refund stay, but skip the hotel — they can find their own accommodation",pts:-80,good:false,reaction:"They find a hotel and demand the cost via Airbnb. Airbnb forces the payment anyway. You save no money, gain a worse review. 'Refund offered but no proactive solution.'",damage:null},
    ],tip:"Real Airbnb forum 2022: a host got accused of bedbugs falsely. Even though no bugs existed, mentioning bedbugs in the listing response permanently scared off bookings. Bedbug claims must be addressed with maximum credibility."},

    {guest:"James & Helena",mood:"DISGUSTED 🤢",icon:"🤢",drama:true,damage:"vomit",scenario:"They arrive at 4 PM. The cleaner came at 11 AM. They send a video: there's vomit in the corner of the master bedroom that the cleaner missed (or didn't enter). 'How did this not get cleaned? We can smell it from the corridor.'",options:[
      {text:"Apologise immediately, send a deep-clean team within 90 minutes, comp the first night, gift £80 dinner voucher to occupy them while it's cleaned",pts:150,good:true,reaction:"Deep clean done by 6:30 PM. They have a lovely dinner. 5 stars: 'Disastrous start, but the host's response was exceptional.' This kind of recovery is gold.",damage:null},
      {text:"Send the original cleaner back with a £20 tip to redo, refund 25%",pts:30,good:true,reaction:"Cleaner does it grudgingly. 3-star review. 'Acceptable response, not exceptional.' Same cleaner makes the same mistake again 3 months later — fire her then.",damage:null},
      {text:"Ask them to send the photo to the cleaner directly, you'll deduct from her pay",pts:-160,good:false,reaction:"They feel passed off. The cleaner texts them defensively. Tense exchange. 1-star review citing 'host made us deal with the cleaner about a hygiene issue'. Cleaner quits.",damage:null},
      {text:"Move them to Notting Hill for first night, deep clean Chelsea overnight",pts:120,good:true,reaction:"Smart. Notting Hill is the cushion. They return to Chelsea spotless. 5 stars. The displacement actually impressed them.",damage:null},
    ],tip:"Inspect cleaner work via photo report — every changeover. It's a £15/changeover cost that prevents £2,000 disasters."},

    {guest:"Mrs Dimitriou",mood:"polite-but-firm 🧐",icon:"🐀",drama:true,damage:"rat",scenario:"Mrs Dimitriou has just sent a video at midnight: a rat ran across the kitchen floor while she was making tea. Just one. She is calm. 'I'm not panicking, but I do need to know what you intend to do about this.'",options:[
      {text:"Apologise sincerely, send pest control first thing, refund 50% of stay, gift breakfast at the local café next morning",pts:150,good:true,reaction:"Pest controller traces it to a hole behind the dishwasher. £380 sealed and treated. Mrs Dimitriou's 5-star review: 'A rat, then exemplary handling. The latter mattered more.'",damage:null},
      {text:"Send pest control, refund 25%, ask her to please not mention it in her review",pts:-120,good:false,reaction:"She mentions it AND your bribery attempt. 'Reasonable response to rat, but tried to silence the review.' This is worse than just owning it.",damage:null},
      {text:"Send a Pest control + offer to rehouse her, but skip the refund",pts:80,good:true,reaction:"She declines rehousing (it's just one rat) but appreciates being asked. 4 stars. Net: rat dealt with, dignity preserved on both sides.",damage:null},
      {text:"Tell her London has rats and suggest she be more careful with food",pts:-340,good:false,reaction:"She's a barrister. She files a Section 4 EHO complaint with the council. Inspector visits. £600 fixed-penalty notice. Listing on the borough's watch list. Public complaint logged.",damage:null},
    ],tip:"London rat populations spike every winter. Quarterly pest contracts cost ~£200/year per property and prevent ~£2,000 in problems."},
  ],

  4: [
    {guest:"Eduard L.",mood:"raging 🤬",icon:"🤬",drama:true,damage:"flood",scenario:"Eduard messages furiously at 6 AM: the en-suite has flooded. Six inches of water across the bathroom and into the bedroom. The guest below has just texted YOU directly: 'Water is coming through my ceiling NOW.' Eduard is shouting into a video.",options:[
      {text:"Turn off mains stopcock remotely via your smart home (you have one), call emergency plumber (£480 callout 6 AM), book Eduard into the Connaught for the night, immediately offer the downstairs neighbour £1,500 for a same-day claim",pts:200,good:true,reaction:"Plumber identifies a burst pipe behind the loo. Fixed by 11 AM. Connaught is gracious. Downstairs neighbour accepts the £1,500 to avoid an insurance claim. Eduard returns at 4 PM to a perfect flat. 5-star review on integrity. £6,200 outlay, but you've prevented a £40k legal mess.",damage:null},
      {text:"Plumber called, towels delivered, hotel booked, but tell the neighbour to claim through their own insurance",pts:30,good:true,reaction:"Neighbour's insurer sues YOUR insurer for subrogation. £8,000 paid out by your premium. Your insurance premium increases 40% next year. Eduard's stay rescued though.",damage:null},
      {text:"Tell Eduard to mop it up while you call a plumber for tomorrow",pts:-380,good:false,reaction:"He posts a video of him mopping while paying £400/night. Listing flagged for 'serious habitability issue'. Downstairs neighbour's ceiling collapses 4 hours later. £52,000 in claims plus civil suit.",damage:null},
      {text:"Plumber + hotel + 100% refund — no negotiation with the neighbour, hope insurers handle it",pts:80,good:true,reaction:"Insurance handles it eventually but it takes 6 months and your premiums rise. Eduard is fine. Neighbour writes a furious complaint to your borough freeholder.",damage:null},
    ],tip:"Most expensive Airbnb scenarios are downstairs water damage. A £200 smart stopcock with remote shutoff prevents £40k disasters. Buy one TODAY."},

    {guest:"@MillaAesthetic",mood:"VICIOUS ✨",icon:"📸",drama:true,damage:"paparazzi",scenario:"Milla has 4.2m TikTok followers. Day 2: she posts a 90-second video tearing the flat apart — 'this so-called luxury Mayfair penthouse'. The video has 800k views in 6 hours and is climbing. The complaints (lift slow, towels 'thin', smoothie blender 'cheap brand') are mostly trivial. Three are legitimate.",options:[
      {text:"Reach out personally (not via management), acknowledge the 3 valid points specifically, fix them within 4 hours, offer to extend her stay by 2 nights free if she's willing to give an honest update video",pts:160,good:true,reaction:"She accepts. Fixes happen. Her follow-up video — 'how this host fixed everything in 4 hours' — does 1.4m views and becomes a positive case study. Inquiries surge 280% for two weeks.",damage:null},
      {text:"Issue a corporate-style legal notice for 'defamation', threaten Airbnb removal",pts:-380,good:false,reaction:"She screenshots the legal threat, posts it. Streisand effect. Original video hits 8m views. Three other influencers post solidarity videos. Listing forced down for 6 weeks while Airbnb investigates.",damage:null},
      {text:"Refund her stay in full silently, hope she takes the video down",pts:-80,good:false,reaction:"She takes the refund AND keeps the video up. Worst of both worlds. £2,400 refunded, video still earning her impressions.",damage:null},
      {text:"Fix the 3 valid items quietly, ignore the video, post nothing yourself",pts:60,good:true,reaction:"Trolls in her comments criticise the trivial complaints. The story dies in 48 hours. No new bookings from it but no cancellations either. Quiet professionalism wins.",damage:null},
    ],tip:"Influencers at scale must be handled like high-profile guests. Never legal-threaten a video creator. Engage authentically; their audience can become advocates faster than detractors."},

    {guest:"Davood R.",mood:"DRUNK 🥴",icon:"🥴",drama:true,damage:"drug_aftermath",scenario:"You arrive for changeover. The 'business stay for 3' has left the master bathroom strewn with cocaine residue on a glass top, four broken champagne flutes, what looks like ketamine in baggies, vomit in the bathtub, and an injured wallaby in the courtyard. You can't even tell what species the wallaby is at first.",options:[
      {text:"Call police non-emergency to document the drugs (you must, legally), call RSPCA for the wallaby, biohazard cleaners, file Airbnb damage claim, do NOT touch the drugs",pts:170,good:true,reaction:"Police take statements (you're complainant, not suspect). Wallaby returns to a sanctuary. Airbnb pays £4,200 in damage. The story makes London Tonight ('London Airbnb hosts wallaby drug party'). Reservations actually surge from morbid curiosity.",damage:null},
      {text:"Quietly clean the drugs yourself, file the rest of the damage, call RSPCA",pts:-180,good:false,reaction:"You touch evidence. Police investigation later (the wallaby was reported stolen) implicates you in 'tampering'. Cleared eventually but listing is suspended 4 months during inquiry.",damage:null},
      {text:"Call the police, call RSPCA, but don't file Airbnb claim — too embarrassing",pts:-60,good:false,reaction:"Damages: £4,200, all out of your pocket. The wallaby story still hits the news. You leave £4k on the table for nothing.",damage:null},
      {text:"Call only RSPCA, ignore the drug residue (will clean later), file Airbnb claim",pts:-220,good:false,reaction:"Cleaner tests positive for cocaine in routine drug screening at her other job. You're investigated. Eventually cleared but the lawyer fees and stress are real. £8,000 net cost.",damage:null},
    ],tip:"Drugs at a property: ALWAYS call police non-emergency 101 first. You become the complainant, NOT the suspect. Failure to report is a criminal offence."},

    {guest:"The Calgary 12",mood:"violent 😈",icon:"😈",drama:true,damage:"drug_aftermath",scenario:"Day 3 of a 4-night booking by 'Mark, business retreat'. Neighbours have called police. Mark booked your Mayfair flat for an alleged 'company offsite for 4 executives'. Police find 12 people, broken furniture, food smeared on every surface, urine in the carpets, fist-sized holes in walls. Estimated damage: £55,000.",options:[
      {text:"File a £55,000 Airbnb damage claim with full documentation, freeholder notification, insurance claim in parallel, civil suit against Mark personally for the gap",pts:200,good:true,reaction:"Airbnb caps payout at £40,000. Insurance covers £8,000 of the £15,000 gap. Civil suit recovers £4,000 from Mark over 2 years. Net out: £3,000 + 14 weeks of lost bookings, but it could have been catastrophic.",damage:null},
      {text:"Settle for £40,000 from Airbnb, drop civil suit, write off the rest",pts:130,good:true,reaction:"Faster, cleaner. £15,000 lost but no two-year stress. Reasonable trade-off. Apartment back online in 8 weeks. Mark blacklisted on the platform.",damage:null},
      {text:"Try to fix it cheaply ourselves, maximise the Airbnb claim",pts:-140,good:false,reaction:"Cheap fixes are visible. Future guests cite 'patches in walls' and 'odd smells'. 6 months of 3-star reviews drive your nightly rate down 40%.",damage:null},
      {text:"Sue Mark personally first, hold off on Airbnb claim",pts:-220,good:false,reaction:"You miss the 14-day Airbnb claim window. Airbnb claim denied. Civil suit against an individual recovers <£3,000. Lose £52,000.",damage:null},
    ],tip:"Real story: Star and Mark King's Calgary home suffered £50-75k damage from an Airbnb 'drug-induced orgy'. They wished it had burned down rather than this. Document EVERYTHING within hours; the 14-day window is real."},

    {guest:"Mr Park",mood:"BEWILDERED 😨",icon:"🔑",drama:true,damage:"brothel",scenario:"You arrive Wednesday morning to clean. Three women in dressing gowns are in the lounge. Two unfamiliar men are leaving. There's a price list on the kitchen counter. Your guest 'Lucia, professional businesswoman' has been running a brothel out of your Mayfair penthouse for the last 5 days.",options:[
      {text:"Leave immediately, call police 101 (not 999 — no immediate danger), record everything, file Airbnb claim, terminate booking through Airbnb support",pts:200,good:true,reaction:"Police arrive within 2 hours, women treated as victims (per UK trafficking guidance), 'Lucia' arrested. Airbnb voids the booking immediately and pays full damages including 14 days of lost income. Your name is on the side of the angels.",damage:null},
      {text:"Confront 'Lucia' directly, demand they leave within an hour, deal with police later",pts:-380,good:false,reaction:"You walked into an active modern slavery situation. Lucia's associates (now alerted) move evidence and victims before police arrive. Police investigation drags YOU in as a complainant who was 'aware of the activity' for an hour. Cleared, but the file is permanent.",damage:null},
      {text:"Call police 999 immediately citing emergency",pts:140,good:true,reaction:"Armed response unit attends. Heavy. Two of the women are confirmed trafficking victims. Police take 6 hours to clear. Booking voided. Right outcome but disproportionate.",damage:null},
      {text:"Pretend you didn't see anything, leave, call Airbnb tomorrow",pts:-460,good:false,reaction:"Failure to report under Modern Slavery Act 2015 is itself an offence. Investigation 6 months later traces your visit through smart lock logs. £15,000 fine and 3 months' suspended sentence. Listing terminated permanently.",damage:null},
    ],tip:"Real story: two London friends returned from holiday to find police had raided their Airbnb to stop a brothel operation. Modern Slavery Act 2015 requires reporting. 101 (non-emergency) for active situations is correct; 999 is for immediate danger."},
  ],

  5: [
    {guest:"Lord Ashworth",mood:"DEMANDING 🧐",icon:"💎",drama:true,damage:"stained_carpet",scenario:"Lord Ashworth (verified peer) arrives. Day 1 message: 'The Persian rug in the drawing room has THREE wine stains the previous guest must have caused. The cleaner missed them. This is unacceptable for a £4,200/night property. I require a 50% refund for the entire 7-night stay or I shall be writing to your trade body.'",options:[
      {text:"Send a Persian-rug specialist cleaner (Bukhara House, £450, same-day) and refund 1 night (£4,200)",pts:160,good:true,reaction:"Stains gone by 4 PM. Lord Ashworth's review: 'Stains found, addressed by master craftsman within hours. Standards.' The £4,200 refund is overshadowed by the rebooking he sends his three friends.",damage:null},
      {text:"Refund 50% of full stay (£14,700) as demanded, no further investigation",pts:-180,good:false,reaction:"Lord Ashworth quietly tells his social circle that this property's host is a soft touch. Three subsequent peers extort similar refunds for trivial issues. £42,000 lost over a year.",damage:null},
      {text:"Refund 1 night (£4,200) and offer a £200 hamper, no specialist cleaner",pts:50,good:true,reaction:"Lord Ashworth is grumpy but mollified. 4-star review noting stains 'addressed but not properly resolved'. Future Persian-rug fans pass on this property.",damage:null},
      {text:"Politely contest the refund — stains pre-existed and are documented in the listing photos",pts:90,good:true,reaction:"He's surprised you have evidence. Apologises privately. 5-star review noting 'thorough record-keeping'. Sometimes data wins respect.",damage:null},
    ],tip:"Photographic inventory before EVERY booking. Date-stamped. Lord Ashworth and his ilk respond well to evidence and badly to capitulation."},

    {guest:"Filming Crew Director",mood:"smug 😏",icon:"🎬",drama:true,damage:"drug_aftermath",scenario:"Day 2: a neighbour sends a photo of vans, lighting equipment, and 40 people on your driveway. Your guest 'Aaron, family stay for 4' has set up a porn shoot. The local press has just arrived because someone tipped off the Daily Mail.",options:[
      {text:"Drive there now, terminate the booking on the spot using the smart lock, give Aaron 30 minutes to clear, call Airbnb mid-eviction for retroactive support",pts:170,good:true,reaction:"Aaron evicts peacefully. Press photographs the eviction. 'London Airbnb host SHUTS DOWN porn shoot' becomes a positive headline. Bookings spike. Airbnb commends you in their newsletter.",damage:null},
      {text:"Let it run its course, file maximum damage claim, ignore the press",pts:-280,good:false,reaction:"Footage from the shoot makes it onto adult sites with your house clearly identifiable. Property values on the street drop. Three neighbours sue for nuisance. £22,000 legal costs.",damage:null},
      {text:"Negotiate with Aaron: he leaves at the end of his booking + £10,000 'damages', no Airbnb involvement",pts:-160,good:false,reaction:"Off-platform settlement violates Airbnb ToS. Listing terminated. Aaron pays £10k but his lawyer claws back £8k via 'duress'. You lose £15k legal.",damage:null},
      {text:"Call Airbnb support immediately, let them handle eviction",pts:60,good:true,reaction:"Airbnb takes 5 hours. Press has time to gather. It works out but the 'host did nothing for 5 hours' narrative dominates. 8% drop in inquiries for 4 weeks.",damage:null},
    ],tip:"Active commercial use of a residential let is grounds for instant termination per Airbnb's 'unauthorised commercial use' clause. Your smart lock + clear evidence = immediate authority."},

    {guest:"Lady Cavendish-Pryce",mood:"sleepless 😩",icon:"😩",drama:true,damage:"silverfish",scenario:"Day 4: Lady C-P sends a calm, devastating message: 'The Master suite has silverfish in the carpet. I haven't slept since Tuesday. They emerge at 3 AM. I'm staying with friends in Belgravia. I expect a full refund AND I expect you to never list this property again until it is properly fumigated.'",options:[
      {text:"Full refund + £200 silk pyjama gift, fumigation by Aardwolf (£900), structural survey for moisture (£600), close listing for 14 days",pts:170,good:true,reaction:"Survey identifies a slow leak under the en-suite floor. Repaired £2,800. Silverfish gone. Lady C-P's review: 'Found an issue. Owner responded with thorough integrity. Returning.' 5 stars.",damage:null},
      {text:"Refund + spray treatment, reopen in 3 days",pts:-80,good:false,reaction:"Spray treats only adults — eggs hatch 14 days later. Next guest sees them. Word spreads. 'Kensington silverfish house' becomes a thing in elite London hosting circles.",damage:null},
      {text:"Refund only the unused nights, treatment done over the weekend",pts:30,good:true,reaction:"She's neutral about the response. 3-star review citing 'silverfish'. 6 months later the issue returns because the underlying moisture wasn't addressed.",damage:null},
      {text:"Suggest she just leaves a light on at night since silverfish hate light",pts:-280,good:false,reaction:"She is genuinely angry now. Posts to Mumsnet's 'Posh Mums in Kensington'. 38,000 reads. 6 weeks of cancelled bookings.",damage:null},
    ],tip:"Silverfish indicate moisture/humidity issues. Treating the symptom (insects) without finding the cause guarantees recurrence."},
  ],

  6: [
    {guest:"Princess Aaliyah",mood:"weeping 😭",icon:"😭",drama:true,damage:"hidden_camera",scenario:"Day 1, 11 PM: Princess Aaliyah's chief of staff calls. The Princess noticed a small black object behind a wall mirror in the master bathroom. Their security detail has identified it as a wireless camera. The Princess is now in the security car. There are 7 hours until her diplomatic engagement at Buckingham Palace.",options:[
      {text:"Drive there now WITH a forensic IT specialist (£800 emergency callout), agree to police involvement, full refund, alternative penthouse at Claridge's at your cost (£14,000), formal apology letter to the embassy",pts:200,good:true,reaction:"Forensic specialist confirms it was an old smoke alarm component (NOT a camera). Police statement filed. Princess accepts the integrity. Embassy receives the apology graciously. The diplomatic relationship survives. The story never goes public. Future royal-tier bookings continue.",damage:null},
      {text:"Refund + Claridge's, but skip the forensic specialist — let police handle it",pts:60,good:true,reaction:"Police investigation takes 6 weeks. During that time, the rumour 'Royal found camera at Covent Garden penthouse' circulates among security details. Six royal-tier bookings cancel. £180,000 lost.",damage:null},
      {text:"Defend yourself — there are no cameras — and ask them to leave the device for inspection",pts:-680,good:false,reaction:"The Princess's security detail's report is filed with the diplomatic protection group. Your name appears in a confidential briefing distributed to FCO. No high-net-worth international bookings ever again. Property's natural ceiling income drops 70%.",damage:null},
      {text:"Refund + Claridge's + sign an NDA with the embassy promising eternal silence",pts:140,good:true,reaction:"Solid handling. Diplomatic crisis averted. The NDA is enforceable. £14k cost recovered via the next 3 royal bookings — the embassy quietly recommends you to other delegations precisely because you handled it discreetly.",damage:null},
    ],tip:"At the £4,000+/night tier, your guests' security details are pre-briefed on you. ONE confirmed-or-suspected privacy incident closes that entire market segment forever."},

    {guest:"Director Markham",mood:"FURIOUS 🤬",icon:"📸",drama:true,damage:"paparazzi",scenario:"Director Markham (Oscar-winning, here for awards season) calls. There are 24 paparazzi outside. Someone — the cleaner, the doorman, an Airbnb employee, anyone — leaked the address. He's trapped inside. He has the BAFTA ceremony in 90 minutes. 'You promised discretion. EXPLAIN.'",options:[
      {text:"Activate the underground supercar exit (£1.7k upgrade pays for itself), get him out via the disused Royal Opera House service tunnel through your prearranged agreement, deny address publicly, full refund",pts:200,good:true,reaction:"He arrives at BAFTA via a different street. The paparazzi photograph an empty front door. He wins. He thanks you in his speech indirectly. Inquiries from other Oscar nominees explode.",damage:null},
      {text:"Hire 6 security guards from 'Steele Group' (£4,800 in 90 mins) to escort him through the front",pts:80,good:true,reaction:"Front-door breakthrough works. Photos of the scrum dominate Mail Online. He's late but makes it. 4 stars. He doesn't book again though — the experience was traumatic.",damage:null},
      {text:"Suggest he leave from the rear fire escape into the alley",pts:-140,good:false,reaction:"Two paparazzi were watching the alley. Photos of him climbing a fire escape go viral. He sues you for breach of the listing's privacy guarantees. £85,000 settlement.",damage:null},
      {text:"Call the Met Police asking for an escort",pts:30,good:true,reaction:"Met sends 2 officers. They escort him out the front door. He's photographed. Photos are tame ('actor leaves quietly with police'). 3 stars. Reasonable but not magic.",damage:null},
    ],tip:"At the £6k/night Covent Garden tier, scenarios like this are why people pay. ONE legitimate emergency-exit success becomes a permanent advertising asset in the right circles."},

    {guest:"Ambassador Volkov",mood:"DIPLOMATIC 🛡️",icon:"🛡️",drama:true,damage:null,scenario:"Ambassador Volkov has booked the entire week. On day 3, his Counter-Surveillance team finds an active listening device behind a painting. They calmly but firmly demand to know who has had access to the property in the past 30 days. The diplomatic incident potential is enormous.",options:[
      {text:"Provide complete cooperation: cleaner records, contractor logs, your own access, smart-lock entry data — every single detail. Full refund. Independent forensic audit at your cost (£6,000). Public statement coordinated with the embassy.",pts:200,good:true,reaction:"Audit finds the device was planted by a former cleaner who had been compromised by a foreign intelligence service. You're not the suspect. The embassy thanks you formally. SIS quietly recommends you to other diplomatic missions.",damage:null},
      {text:"Provide records but resist the forensic audit on cost grounds",pts:-280,good:false,reaction:"The Ambassador's report classifies you as 'uncooperative'. FCO alert distributes through embassies. Six diplomatic bookings cancel. £270,000 lost over 8 months.",damage:null},
      {text:"Provide minimum legal records, hire a lawyer, refuse forensic audit",pts:-460,good:false,reaction:"Embassy declares the property 'compromised'. Listing pulled by Airbnb pending investigation. Your cleaner is interviewed by police; she names you as 'aware'. Cleared eventually but the file follows you.",damage:null},
      {text:"Full cooperation + forensic audit + free 12-month exclusive offer to the embassy",pts:160,good:true,reaction:"Generous beyond expectation. Embassy declines the 12-month offer politely (sovereignty issue) but the gesture is logged. SIS recommendation follows. Three subsequent diplomatic bookings.",damage:null},
    ],tip:"Counter-surveillance findings at diplomatic stays are uncommon but consequential. Total transparency is the only path. Your installed cameras (security, fire, etc.) must be impeccably documented and visible to inspect."},
  ],
};

// Merge into ALL_QUESTIONS
Object.keys(EXTRA2_QUESTIONS).forEach(k => {
  if (!ALL_QUESTIONS[k]) ALL_QUESTIONS[k] = [];
  ALL_QUESTIONS[k] = ALL_QUESTIONS[k].concat(EXTRA2_QUESTIONS[k]);
});
