// Extra scenarios — merged into ALL_QUESTIONS at runtime
const EXTRA_QUESTIONS = {
  // ─────────────────────────────────────────────────────────────────
  // PROPERTY 1 — NOTTING HILL STUDIO
  // ─────────────────────────────────────────────────────────────────
  1: [
    {guest:"Edmund T.",mood:"posh & confused 🐎",icon:"🐎",drama:true,scenario:"Edmund arrives by horsebox. He's brought his pony, Buttercup. 'Your listing said \"pet-friendly\"! She's a small horse, really. Where shall I put her? The kitchen?'",options:[
      {text:"Politely but firmly explain that 'pet-friendly' covers cats and small dogs only, refund his stay, help him find an equestrian B&B",pts:140,good:true,reaction:"Edmund accepts. 'Right. Yes. Of course. Sorry old chap.' Buttercup goes to a livery yard. Edmund books your Kensington stables for next year. Future business secured."},
      {text:"Say yes and let her stay in the small garden — it's just one night",pts:-280,good:false,reaction:"Buttercup eats £400 of plants, tramples a flowerbed, and your downstairs neighbour reports you to the council. Three separate complaints filed. RSPCA visits. The horse was also unhappy."},
      {text:"Charge a £200 'unusual pet' fee and let it happen",pts:-200,good:false,reaction:"Buttercup destroys the parquet flooring, leaves a deposit on the carpet, and the smell never fully leaves. £1,800 in damages. Insurance refuses to cover horses."},
      {text:"Refuse and tell him to read the listing properly next time",pts:-60,good:false,reaction:"Edmund leaves a 1-star review. 'Listing said pet-friendly. Host was rude.' Technically you were right but tone matters in hospitality."},
    ],tip:"'Pet-friendly' must explicitly state size and species limits. 'Cats and small dogs under 15kg' leaves no room for ponies."},

    {guest:"Hans & Lieselotte",mood:"clueless 😅",icon:"😅",drama:false,scenario:"German guests Hans and Lieselotte send a panicked photo: they've put loose tea leaves AND tea bags directly inside the kettle — water, leaves and all — and switched it on. The kettle is now full of brown sludge.",options:[
      {text:"Reply with a friendly tutorial video on how British kettles work, send a £15 voucher for a teapot from John Lewis, and laugh about it together",pts:130,good:true,reaction:"They howl with laughter. The video becomes a running joke through their stay. 5-star review: 'Funniest, kindest host. Taught us proper tea.' They book again next year."},
      {text:"Charge them £40 for a replacement kettle and lecture them on basic appliance use",pts:-140,good:false,reaction:"Hans, mortified, leaves a 2-star review: 'Host was condescending about a simple mistake.' Six future bookings cancel after reading it."},
      {text:"Tell them to just rinse it out and move on",pts:60,good:true,reaction:"Pragmatic. Slightly transactional. 4 stars. 'Helpful host, slightly cold.'"},
      {text:"Send a cleaner over to descale the kettle and add it to your maintenance log",pts:80,good:true,reaction:"Professionally handled. The kettle's saved. Mild overkill for a £25 kettle. 4 stars."},
    ],tip:"Cultural confusion is a comedy goldmine, not a hospitality crisis. Lean into it warmly — these guests rebook and refer."},

    {guest:"Aamir K.",mood:"embarrassed 😓",icon:"😓",drama:true,scenario:"Aamir messages 30 minutes before check-in: 'My card has just been declined three times on the booking. I'm at Heathrow. I have £2,000 cash but Airbnb won't let me pay that way. What do I do?'",options:[
      {text:"Call Airbnb on his behalf, request alternative payment, suggest he use a different card or PayPal via the platform — never accept off-platform cash",pts:160,good:true,reaction:"Airbnb's resolution centre helps within 20 minutes. Card was flagged as 'foreign transaction', resolved with one phone call. Aamir checks in on time. He never forgets the support."},
      {text:"Tell him to bring the cash and you'll handle the booking through Airbnb after",pts:-260,good:false,reaction:"Off-platform payment violates Airbnb's terms. Account suspended for 30 days. £4,200 in lost bookings. Aamir's stay also voided."},
      {text:"Say there's nothing you can do, the platform handles payments",pts:-100,good:false,reaction:"Aamir spends 4 hours stranded at Heathrow before figuring it out himself. 1-star review: 'Host abandoned me when I needed help.'"},
      {text:"Offer to call his bank with him on speaker — banks often clear travel-flagged cards instantly",pts:130,good:true,reaction:"His bank unblocks the card in 90 seconds. Aamir is amazed at the practical help. 5-star review specifically about 'going beyond what was needed'."},
    ],tip:"Card declines on booking are common — banks flag foreign transactions automatically. Helping the guest call their bank is fast, free, and creates fans."},

    {guest:"The Cleaner Crisis",mood:"language barrier 🤷",icon:"🤷",drama:true,scenario:"Your new cleaner Maria texts: 'PROBLEMA NO ENTIENDO LISTA' with a photo of your check-out instructions. She speaks Polish-Spanish only. You speak neither. Google Translate is showing 'service temporarily unavailable'.",options:[
      {text:"Send simple emoji-based instructions (🛏️✅ 🚿✅ 🗑️➡️) plus video clips you record on your phone walking through each task",pts:170,good:true,reaction:"Maria sends back thumbs-ups and completion photos. The clean is perfect. You permanently switch to picture-based briefs. Half your future cleaners speak limited English. Brilliant solution born from necessity."},
      {text:"Try DeepL, Bing, Yandex, and any other translation service that's still up",pts:130,good:true,reaction:"DeepL Polish works. You translate your full briefing. Maria does a great job. You discover DeepL is more reliable than Google for Slavic languages."},
      {text:"Wait for Google Translate to come back online",pts:-160,good:false,reaction:"It's down for 6 hours. Maria leaves without finishing. The next guest arrives to a half-cleaned flat. £200 emergency clean. 1-star review."},
      {text:"Give up and clean it yourself",pts:-40,good:false,reaction:"You complete the clean but it costs you 4 hours of work, miss two important calls, and your other property gets neglected too. Bad time management."},
    ],tip:"Picture-based briefs work across every language. Take photos of perfect setups and use them as your standard cleaning template."},

    {guest:"Dawn check-out",mood:"horrified 😱",icon:"😱",drama:true,scenario:"Your cleaner Sofia calls in tears: 'Madam, I'm so sorry. I've thrown something away. I thought it was old. It was a wig. A very, very expensive wig. The guest is messaging now.' The guest is a Channel 4 newsreader.",options:[
      {text:"Take full responsibility, offer to fully fund replacement (£600 average), apologise warmly to both guest and cleaner, file an incident on Airbnb",pts:170,good:true,reaction:"Newsreader is incredibly understanding. 'These things happen. Thank you for being grown-up about it.' She tweets thanks. Three viewers book your flat after seeing the tweet."},
      {text:"Insist the cleaner pays — it was her mistake",pts:-200,good:false,reaction:"Sofia quits. The cleaner agency you used blacklists you. Two other cleaners refuse jobs after hearing. You've lost your entire cleaning network in one move."},
      {text:"Try to retrieve it from the bins yourself",pts:0,good:true,reaction:"You find it. Mostly. It's now coffee-grounds-flavoured. The guest declines. You pay for replacement anyway. Slapstick effort, professional outcome."},
      {text:"Tell the guest she should have left a note about valuables",pts:-180,good:false,reaction:"'Are you really blaming me for your cleaner throwing my £800 wig away?' The newsreader posts the exchange to her 200k Twitter followers. Ratio'd. Bookings tank for a month."},
    ],tip:"When your team makes a mistake, you own it publicly and protect them privately. The opposite breeds fear, hidden errors, and worse outcomes."},

    {guest:"Charlotte W.",mood:"distressed 😟",icon:"😟",drama:false,scenario:"On checkout day Charlotte writes: 'I've left a small wrapped item in the bedside table — please could you post it back to me? It's my late grandmother's pendant. I'd be devastated to lose it.'",options:[
      {text:"Personally retrieve it before the cleaner arrives, photograph it, package securely, post tracked the same day",pts:180,good:true,reaction:"Charlotte cries when she opens the package. 5-star review with the most heartfelt message you've ever received. She refers her entire book club. Six bookings result."},
      {text:"Ask the cleaner to 'keep an eye out for a pendant'",pts:-150,good:false,reaction:"Cleaner finds it, doesn't realise it's the pendant in question, files it in the lost & found box where it sits for 3 months. Charlotte's grandmother's pendant: lost. 1-star review."},
      {text:"Tell her to send a courier — you can't do post runs",pts:-80,good:false,reaction:"Courier costs £45. Charlotte pays it but is wounded by the lack of warmth. 3 stars. 'Helpful but unsentimental.'"},
      {text:"Charge a £20 'lost item handling fee' and post it",pts:-60,good:false,reaction:"'You're charging me to recover my dead grandmother's pendant?' Charlotte tells everyone she knows. Word travels. Your reputation in west London takes a hit."},
    ],tip:"Sentimental items are reputation-makers. The £8 it costs to post a pendant returns 100x in word-of-mouth referrals."},

    {guest:"The Hartwells",mood:"furious 😤",icon:"😤",drama:true,scenario:"Mrs Hartwell texts at 11 PM: 'There is BLOOD on the bed sheets. Actual blood. We are in shock. We're getting straight back in the Uber and we will be filing a complaint. This is the most disgusting thing I have ever experienced.'",options:[
      {text:"Apologise without excuses, offer immediate full refund, send a hotel voucher for tonight, fire your cleaner if this is a pattern, schedule a deep clean",pts:200,good:true,reaction:"Mrs Hartwell, in a hotel an hour later, is calmer. 'Thank you for not gaslighting me.' She rebooks for next month at a different property of yours. Recovery complete."},
      {text:"Suggest it might be old red wine — sometimes it looks similar",pts:-280,good:false,reaction:"It was definitely blood (a previous guest's nosebleed never properly addressed by your cleaner). Mrs Hartwell sends photos to a national paper. The story runs. Devastating."},
      {text:"Offer a 30% discount and ask them to stay anyway",pts:-200,good:false,reaction:"They refuse and rightly so. 1-star review with photos. Airbnb removes the listing pending investigation. Eight days of zero bookings."},
      {text:"Send fresh sheets and a complimentary hamper, change beds yourself if needed, offer 50% refund on top",pts:130,good:true,reaction:"Hartwells stay. They're shaken but appreciate the effort. 3-star review is fair given what happened. Recoverable."},
    ],tip:"Bed linen is non-negotiable. A single hair, stain, or mark requires a complete bed strip. There is no in-between standard."},
  ],

  // ─────────────────────────────────────────────────────────────────
  // PROPERTY 2 — SHOREDITCH LOFT
  // ─────────────────────────────────────────────────────────────────
  2: [
    {guest:"The Brixton Boys",mood:"big energy 🎵",icon:"🎵",drama:true,scenario:"It's 2 AM on a Saturday. Your noise sensor pings 110dB. Your downstairs neighbour calls: 'There are 60 people in your flat. There's a DJ. I think I saw a fog machine. I'm calling the police now.'",options:[
      {text:"Call the lead booker immediately, give them 10 minutes to disperse, document everything via the noise sensor, call Airbnb's 24/7 trust & safety line right after",pts:220,good:true,reaction:"They clear out fast. Police arrive after — one warning. Airbnb terminates the booking and refunds you the cleaning fee. The party damages: minimal. You file an AirCover claim for the £300 deep-clean."},
      {text:"Pretend you didn't hear the alert and let it run its course",pts:-380,good:false,reaction:"Police break it up. The flat is destroyed: £4,200 damages. Your council licence is suspended pending review. Two neighbours sue. The worst night of your hosting career."},
      {text:"Drive over yourself and try to break it up alone",pts:-120,good:false,reaction:"You're shoved at the door by a bouncer they brought. Police arrive anyway. Documentation is incomplete. Insurance pushes back on the claim. Don't go alone."},
      {text:"Call the police first, then notify Airbnb",pts:160,good:true,reaction:"Police clear the flat in 25 minutes. Two arrests. The booker's account is terminated. You file claims and recover £2,800 in damages. Effective but slower than calling them first."},
    ],tip:"Modern noise sensors aren't optional at the loft level. They pay for themselves the first time they catch a party at 11 PM instead of 3 AM."},

    {guest:"Damien R.",mood:"squatting 😈",icon:"😈",drama:true,scenario:"Damien booked for 5 nights, paid for 5 nights, has now stayed for 11 nights. He stops responding to messages. The flat is technically still occupied — your next guest can't check in. Police say they 'can't get involved unless you have proof of trespass'.",options:[
      {text:"File the Airbnb overstay claim with full evidence, contact a specialist short-let solicitor (£300 retainer), serve formal notice, stay calm and document",pts:210,good:true,reaction:"The solicitor's letter alone scares him out within 48 hours. AirCover settles the lost booking income. £1,200 recovered. You add an overstay clause to your standard welcome guide."},
      {text:"Change the locks while he's out at the pub",pts:-300,good:false,reaction:"He returns, can't get in, calls the police. Police side with him — that's illegal eviction. You're now facing a criminal charge. The case takes months."},
      {text:"Offer him £500 to leave by tonight",pts:-160,good:false,reaction:"He takes the £500 and stays anyway. Now you've paid him to squat. He's also told 3 friends, who book to do the same."},
      {text:"Wait it out — he'll leave eventually",pts:-220,good:false,reaction:"He stays 19 days. Your next 4 bookings are cancelled. £3,400 in lost income. He eventually leaves having damaged the door. Insurance disputes the claim."},
    ],tip:"UK short-let overstays after 28 days create tenancy rights. Act before that window closes — formal solicitor's letter is your best tool."},

    {guest:"The Cleaner & The Watch",mood:"misunderstood 😬",icon:"😬",drama:true,scenario:"Your cleaner Anya messages with photos: 'Found this in pillowcase, I put it in safe drawer for guest to collect'. It's a gold Patek Philippe worth £85,000. The guest is messaging you simultaneously, panicking.",options:[
      {text:"Photograph the watch in your possession, message the guest with photos and tracking details, courier it via insured Royal Mail Special Delivery",pts:240,good:true,reaction:"The guest (a hedge fund manager) is so impressed he books your Mayfair penthouse for 30 nights at full rate. £18,000 of bookings born from one cleaner's integrity."},
      {text:"Tell the guest the cleaner found 'a watch' and ask him to describe it for verification",pts:170,good:true,reaction:"Sensible verification. He provides serial number — matches. Watch returned. Guest impressed by the security check. Professional handling. Strong outcome."},
      {text:"Drop the watch off at the Airbnb lost-and-found — let them handle it",pts:-180,good:false,reaction:"Airbnb has no specific protocol for £85k watches. It sits in a depot for 11 days. Guest furious. AirCover doesn't cover the panic."},
      {text:"Suggest he comes back to collect it personally for security reasons",pts:80,good:true,reaction:"He's happy to. Comes by the same day. You serve him a proper coffee while he completes verification. Builds personal relationship. Solid."},
    ],tip:"Forgotten valuables are reputation-makers. A clean, photographed, insured return is the gold standard — and the guests who own £85k watches notice."},

    {guest:"The Vomit Terrace",mood:"mortified 😵",icon:"😵",drama:true,scenario:"Your cleaner sends a photo at 9 AM: the rooftop terrace is covered in vomit. Three loungers, the BBQ, half the planters. Your check-in is at 3 PM. Outside cleaning specialists are quoting £450 and 'maybe by 6 PM'.",options:[
      {text:"Pay the £450 for emergency professional clean, message the incoming guest proactively offering 1-hour delayed check-in with a £30 voucher for inconvenience",pts:170,good:true,reaction:"Incoming guest appreciates the heads-up. 'Thanks for being upfront.' Terrace is restored by 4 PM. Stay goes well. 5-star review specifically mentions communication."},
      {text:"Quickly pressure-wash it yourself with a hose",pts:-200,good:false,reaction:"You spread it around. The smell stays for days. Next guest leaves a 2-star review: 'Subtle but persistent unpleasant smell on the terrace.' Repair effort: £900 in lost bookings."},
      {text:"Block the terrace off with a sign saying 'maintenance' and keep quiet",pts:-160,good:false,reaction:"The terrace was the guest's main reason for booking the loft. They notice the cover-up. 1-star review: 'Host hid issues from us.' Eight cancellations follow."},
      {text:"File a damage claim with the previous guest, then organise the clean",pts:130,good:true,reaction:"Previous guests pay £450 via AirCover within 4 days. Professional clean done. Incoming guests warned. Everyone handled well."},
    ],tip:"Speed of cleanup beats cost of cleanup. Professional emergency services exist for exactly these moments — relationship-build with one before you need them."},

    {guest:"Tom & Sage",mood:"hipster 🎨",icon:"🎨",drama:false,scenario:"Sage, a 'wellness influencer', sends a 9-paragraph message before check-in. She requires: alkaline water filtration, a himalayan salt lamp, ALL surfaces wiped with white vinegar (no chemicals), zero EMF in the bedroom, and 'energetically cleansed' bed linen. Her booking is 1 night.",options:[
      {text:"Politely explain you can offer alkaline water and salt lamp at £30 add-on; the rest is beyond what's possible for a single night; let her cancel free if she prefers",pts:140,good:true,reaction:"She cancels respectfully. Books a wellness-specific Airbnb instead. You learn that's not your market and don't waste 3 hours of effort. Time saved is income."},
      {text:"Bend over backwards to accommodate everything",pts:-120,good:false,reaction:"You spend £180 on supplies and 4 hours preparing. She arrives, finds 'subtle EMF', leaves. 1-star review: 'Host did not understand wellness needs.' Soul-destroying."},
      {text:"Ignore the message and let her arrive to the standard setup",pts:-200,good:false,reaction:"She films a 12-minute TikTok review of all the violations. 480k views. Bookings drop 30% for the next month."},
      {text:"Charge a £100 'wellness preparation fee' and try to deliver",pts:-80,good:false,reaction:"You deliver 70%. She finds the missing 30%. 2-star review. The £100 fee makes it look like a transactional bait-and-switch."},
    ],tip:"Saying 'we can't do that' professionally is not failure — it's qualifying out a guest who would have cost you reviews. Set your scope."},
  ],

  // ─────────────────────────────────────────────────────────────────
  // PROPERTY 3 — CHELSEA TOWNHOUSE
  // ─────────────────────────────────────────────────────────────────
  3: [
    {guest:"The Chen Family",mood:"lost in translation 🌐",icon:"🌐",drama:true,scenario:"The Chen family arrive — 6 of them — speak only Mandarin. Their interpreter just texted: 'Family emergency, can't make tomorrow.' They have 4 days here. They look at you, you look at them, and Google Translate is timing out.",options:[
      {text:"Use written Mandarin via your phone (DeepL works), share emergency contacts in their script, hire a freelance Chinese-speaking concierge for 4 days at £200/day",pts:200,good:true,reaction:"The £800 investment buys 4 days of seamless translation. Mr Chen tips you £400 personally. Books your Mayfair penthouse for next year. Network gold."},
      {text:"Hand them a printed welcome sheet and let them figure it out",pts:-80,good:false,reaction:"They miss the bin schedule, lock themselves out twice, set off the smoke alarm cooking. They leave a polite 3-star review. You miss the chance to wow them."},
      {text:"Use point-and-show: prepare picture cards for every common request (towels, bins, heating, etc.) and pin them to the fridge",pts:170,good:true,reaction:"The Chens love the effort. Picture cards become your standard. They leave glowing 5 stars and recommend you to two visiting families."},
      {text:"Tell them to use Google Translate themselves",pts:-140,good:false,reaction:"Google Translate is still patchy with Mandarin colloquialisms. They struggle for 4 days. 2-star review: 'Cold, technology-dependent host.'"},
    ],tip:"Translation apps fail at exactly the wrong moments. Picture cards, freelance interpreters, and pre-printed multi-language welcome sheets are your insurance policy."},

    {guest:"Mrs Whitmore",mood:"accusatory 🧐",icon:"🧐",drama:true,scenario:"Mrs Whitmore checks out then messages 24 hours later: 'I can't find my £3,000 diamond earring. I last saw it on the bedside table. Your cleaner clearly took it. I want it returned or I'll be filing a police report.'",options:[
      {text:"Check the cleaner's photo log (you require post-clean photos), search the property thoroughly yourself, ask Mrs Whitmore for the time/date last seen, contact your insurance",pts:200,good:true,reaction:"You find it lodged behind the headboard while doing the search. Mrs Whitmore is mortified. You don't gloat. 5-star review: 'Host was patient and methodical when I'd already accused his team.'"},
      {text:"Defend the cleaner aggressively — she's been with you for years",pts:-140,good:false,reaction:"Without evidence, your defence sounds dismissive. Mrs Whitmore files a police report. Three days of CID interviews. Earring eventually found in her own car. No apology offered. Reputation damaged."},
      {text:"Pay her £3,000 to make the accusation go away",pts:-300,good:false,reaction:"Word spreads in chelsea circles that you pay out on accusations. Three more guests 'lose' valuables in the next month. £8,000 paid out unnecessarily."},
      {text:"Politely refuse to engage until she files via Airbnb's formal process and provides proof of value",pts:130,good:true,reaction:"Boundaries set. Airbnb mediation requires receipts she can't produce. Case dropped. Cleaner protected. Process followed."},
    ],tip:"Photo evidence on every clean protects your team from false accusations. £15/month of cloud storage is cheaper than £3,000 in unfounded liability."},

    {guest:"Yorkshire Yvonne",mood:"sneaky 🐕",icon:"🐕",drama:true,scenario:"Yvonne booked stating she has 'one small Yorkshire terrier'. Your doorbell camera shows her arrival: she has THREE Yorkshire terriers, plus two larger dogs, plus what appears to be a parrot. Your listing allows ONE small dog.",options:[
      {text:"Confront her at check-in calmly: 'The booking is for one dog. I can offer two options — one dog stays and the others go to Bunty's Boarding 5 minutes away, or we cancel free of charge.'",pts:180,good:true,reaction:"She's caught fairly. 'Fine, fine. I'll board them.' She does. The visit goes well. 4-star review. Yvonne never tries this on you again — but you've added a 'pet number verification' clause."},
      {text:"Pretend you didn't see the camera footage and let it go",pts:-260,good:false,reaction:"3 dogs and a parrot in a Chelsea townhouse for a week. £1,200 in damages. Carpet replacement. The parrot is missing on checkout. RSPCA call you about that one."},
      {text:"Charge a retroactive £400 'unauthorised pet fee' via Airbnb",pts:80,good:true,reaction:"AirCover backs you up — Yvonne's account is flagged. £400 paid. Damages still happen but you're partially compensated. Decent outcome."},
      {text:"Demand she leaves immediately or you'll call Airbnb",pts:60,good:true,reaction:"She leaves. 1-star review: 'Host turned us away over a paperwork issue.' But your property is intact. Defensible decision."},
    ],tip:"Doorbell cameras at check-in catch pet-violations, extra-guest stuffing, and unauthorised events at the moment they begin. Verify, then act calmly."},

    {guest:"The Wine Crime",mood:"horrified 😱",icon:"😱",drama:false,scenario:"Your cleaner photographs an enormous red wine stain across your antique chesterfield sofa. Estimate: £2,400 to professionally restore. The previous guests, the Goldbergs, swore there was no incident.",options:[
      {text:"File a discreet AirCover claim with photos timestamped within an hour of checkout, share with the Goldbergs without accusation, let Airbnb mediate",pts:200,good:true,reaction:"AirCover sides with you. Goldbergs admit the incident under questioning. Sofa restoration funded. They leave a 4-star review which surprises everyone — they appreciated the calm process."},
      {text:"Message the Goldbergs furiously demanding immediate payment",pts:-150,good:false,reaction:"They deny it harder. Block you. Without mediation you have no leverage. £2,400 from your pocket. Lesson learned."},
      {text:"Replace the chesterfield instead of restoring — easier",pts:-250,good:false,reaction:"Replacement is £4,800. The sofa was an heirloom. Insurance covers depreciated value only. £3,200 personal loss."},
      {text:"Try home remedies — salt, bicarb, Vanish — for 3 hours",pts:-120,good:false,reaction:"You make it worse. The sofa is now ringed in lighter patches. Restorers refuse to touch it. £2,400 becomes £4,000."},
    ],tip:"Time-stamped post-checkout photos are admissible evidence in AirCover claims. Without them, your claim is your word against theirs."},

    {guest:"The Forgotten Box",mood:"frantic 📦",icon:"📦",drama:true,scenario:"A guest who left 4 days ago messages: 'I've left a small wooden box in the wardrobe. Top shelf. Please don't open it. It's important to me. I'll send a courier tomorrow.' Three guests have stayed since.",options:[
      {text:"Check immediately, retrieve the box if found, store it securely in your office, photograph the unopened box for proof, courier same-day",pts:170,good:true,reaction:"You find it intact (the cleaner had moved it to lost & found). Couriered same day. Guest sends a £100 thank-you. You never learn what was inside. Some mysteries stay mysteries."},
      {text:"Tell him you'll 'have a look' and put it on tomorrow's list",pts:-100,good:false,reaction:"Tomorrow's list never reaches it. Box is binned. Guest is devastated — it contained his late father's pocket watch. Word travels fast. 1-star, public, brutal."},
      {text:"Open it to verify contents before storing — it's your property after all",pts:-220,good:false,reaction:"It contained his late father's ashes. He's traumatised that a stranger opened it. Litigation threatens. Your insurance won't cover emotional damages."},
      {text:"Charge a £40 retrieval fee plus courier costs",pts:-40,good:false,reaction:"He pays it but is bruised. 3 stars. 'Felt nickel-and-dimed during a sentimental moment.'"},
    ],tip:"Sealed personal items remain sealed. The trust they're handed back un-investigated is more valuable than satisfying your curiosity."},
  ],

  // ─────────────────────────────────────────────────────────────────
  // PROPERTY 4 — MAYFAIR PENTHOUSE
  // ─────────────────────────────────────────────────────────────────
  4: [
    {guest:"Anonymous A-lister",mood:"discreet 🕶️",icon:"🕶️",drama:true,scenario:"A booking comes in under 'A. Smith'. Your concierge spots him at check-in: a Hollywood actor currently in tabloids over a divorce. The Sun calls within an hour: 'We'll pay £15,000 for confirmation he's there.'",options:[
      {text:"Refuse, document the call, brief your team on confidentiality, send the actor a discreet note offering enhanced privacy support",pts:280,good:true,reaction:"He's so grateful he books your penthouse for 6 months over the next 2 years. The tabloid tries 4 more times — never gets confirmation. Your reputation in HNWI circles is made by this one decision."},
      {text:"Take the £15,000 — he'll never know where it came from",pts:-450,good:false,reaction:"His PR team identifies the source (they always do). You're added to a celebrity blacklist. Mayfair bookings drop 60% within 3 months. £200,000 in lifetime revenue lost for £15k."},
      {text:"Offer the tabloid a 'no comment' but accept their card 'for future contact'",pts:-120,good:false,reaction:"Even appearing willing to talk is enough. The actor's PR firm hears about it. You're soft-blacklisted. No headlines but bookings dwindle quietly."},
      {text:"Tell the actor about the call so he can decide — full transparency",pts:230,good:true,reaction:"He takes the information calmly. Adjusts his security. Tips your concierge £1,000. You've built trust. He recommends you to two other A-list clients."},
    ],tip:"At Mayfair level, your reputation in private circles matters more than any amount of money. Discretion isn't a service tier — it's the foundation."},

    {guest:"The Crypto Kid",mood:"techie 💻",icon:"💻",drama:true,scenario:"A guest calling himself 'CryptoKing' wants to pay £8,000 for 4 nights — but only via Bitcoin, sent directly to your wallet. Airbnb's standard payment 'isn't decentralised enough' for him. He says it's urgent.",options:[
      {text:"Politely refuse — accept only Airbnb's processed payment. Don't engage with off-platform crypto.",pts:180,good:true,reaction:"He huffs and pays via Airbnb anyway. Turns out CryptoKing is a 19-year-old testing whether you'd take an obvious laundering attempt. Your refusal is reported to him by his lawyer father — who books your property genuinely the next month."},
      {text:"Accept the Bitcoin — £8,000 is £8,000",pts:-400,good:false,reaction:"Your bank flags the transaction. HMRC investigation begins. Six months of audits. Legal fees: £14,000. Suspended Airbnb account. The Bitcoin was traced to a sanctioned wallet."},
      {text:"Counter-offer: Airbnb payment plus a £500 'crypto convenience' fee",pts:-100,good:false,reaction:"He laughs and walks. Your fee suggestion is reported to Airbnb who flag your account for unusual fee structures. Warning issued."},
      {text:"Forward his message to Airbnb's trust & safety team",pts:160,good:true,reaction:"They thank you. He's flagged across the platform. Two days later he tries this on three other hosts who are now warned. Community service."},
    ],tip:"Off-platform payments — crypto, cash, bank transfer, gift cards — break Airbnb's terms and remove all your protections. There's no exception worth taking."},

    {guest:"Ambassador Chen",mood:"diplomatic 🛡️",icon:"🛡️",drama:true,scenario:"Ambassador Chen books for 5 nights. His advance team arrives 24 hours early demanding: full security sweep, 3 staff in the building 24/7, 4 close-protection officers, removal of your art collection (security risk), and a written confidentiality agreement covering all your staff. Standard rate.",options:[
      {text:"Welcome the requirements with a counter-proposal: a £6,000 diplomatic surcharge covering all logistics, formal agreement signed, full cooperation",pts:240,good:true,reaction:"His office accepts immediately ('We expected as much'). The £6k surcharge covers your costs handsomely. Ambassador Chen privately recommends your property to two other embassies. New niche unlocked."},
      {text:"Refuse — too much hassle for one booking",pts:-100,good:false,reaction:"Ambassador's office moves on without comment. You learn 6 months later that they normally pay £12,000+ for diplomatic stays. Niche missed."},
      {text:"Accept all demands at standard rate — diplomatic guests bring prestige",pts:-180,good:false,reaction:"You absorb £4,500 in additional costs. Your art is in storage for 2 weeks (£800). Staff overtime: £1,200. Net loss: £6,500. Prestige doesn't pay mortgages."},
      {text:"Push back hard on the art removal — your collection stays",pts:60,good:true,reaction:"They negotiate. Two pieces removed, the rest covered with sheets. Workable compromise. Booking proceeds. Modest profit."},
    ],tip:"Diplomatic bookings are a real market with predictable structures. Your Mayfair property qualifies — research the protocols and price accordingly."},

    {guest:"The Card Crisis",mood:"anxious 💳",icon:"💳",drama:true,scenario:"A high-value 7-night booking just came in: £14,000. Your payment processor sends an alert: 'Card declined — possible fraud. Hold issued.' The guest is messaging Airbnb support saying it was approved on her end. Check-in is in 6 hours.",options:[
      {text:"Contact your premium payment processor's fraud line directly, request manual review with the booking details, alert Airbnb of the situation, prepare a backup payment route for the guest",pts:200,good:true,reaction:"Stripe Premium clears it within 30 minutes — the card was flagged due to a Saudi Arabia origin. £14,000 booking saved. The guest is grateful for the personal handling. Books again next month."},
      {text:"Accept the booking anyway and chase payment after",pts:-280,good:false,reaction:"The card was genuinely fraudulent. £14,000 of services delivered. Stripe charges back. Police report. 4 weeks of fraud investigation. Devastating."},
      {text:"Cancel the booking immediately to protect yourself",pts:-150,good:false,reaction:"Card was actually legitimate. Saudi guest is offended. 1-star review: 'Host treated me as a criminal because of my country.' Discrimination accusation. Airbnb investigates."},
      {text:"Wait for the guest to sort it out themselves",pts:-100,good:false,reaction:"She doesn't. Misses check-in. Both of you lose. The guest blames you for not warning her. Mediocre outcome avoidable with proactive handling."},
    ],tip:"Premium payment processing isn't an upgrade — at this price point, it's load-bearing infrastructure. The £450/year saves £14,000 incidents."},

    {guest:"Furniture Fraud",mood:"entitled 🤨",icon:"🤨",drama:false,scenario:"Mrs Petrova checks out and politely asks: 'Where do I send the courier to collect the Hans Wegner armchair? It belongs with my collection — I'll be taking it.' The chair is yours. Worth £4,500. She seems entirely sincere.",options:[
      {text:"Calmly clarify: the chair stays with the property; share photos from the listing showing it; offer a recommendation to her dealer for sourcing one",pts:160,good:true,reaction:"She's mortified. 'I do apologise — I confused myself with my Geneva flat.' She actually buys one through your introduction (£300 commission to you). 5-star review with mention of your 'unflappable diplomacy'."},
      {text:"Allow it — £4,500 is recoverable through insurance",pts:-380,good:false,reaction:"Insurance refuses — 'voluntary surrender of property'. The chair is gone. Mrs Petrova thanks you on her way out, tip well-given. £4,500 from your pocket."},
      {text:"Threaten her with police involvement immediately",pts:-220,good:false,reaction:"She was genuinely confused (early dementia, you later discover). Her family lodge a formal complaint about your tone. Public review: 'Aggressive host targeted my elderly mother.'"},
      {text:"Charge her £4,500 via Airbnb if she insists on taking it",pts:120,good:true,reaction:"She declines once she sees the price. 'Oh, well, never mind!' Chair stays. No drama. Acceptable resolution."},
    ],tip:"Confusion at checkout — including about furniture ownership — happens more than you'd think with mature HNWI guests. Stay calm, be specific, recover gracefully."},
  ],

  // ─────────────────────────────────────────────────────────────────
  // PROPERTY 5 — KENSINGTON MANSION
  // ─────────────────────────────────────────────────────────────────
  5: [
    {guest:"The Hunt Set",mood:"horse-mad 🐎",icon:"🐎",drama:true,scenario:"Lady Cavendish-Pryce arrives for the Royal Ascot weekend with her booking party. She has also brought her four horses 'for a quick gallop in Hyde Park'. Without your stables installed, you have 4 horses standing on your gravel driveway.",options:[
      {text:"Apologise — your stables are not yet operational. Liaise with Hyde Park stables (you have a number on file for moments like this), get the horses safely housed within 90 minutes",pts:190,good:true,reaction:"Lady Cavendish-Pryce is grateful for the rescue. She personally tips your concierge £500. Books your Covent Garden penthouse for next year (still in planning). Royal-tier referral guaranteed."},
      {text:"Tell her she can't bring horses without prior arrangement",pts:-180,good:false,reaction:"She's furious — your listing mentioned 'equestrian-friendly grounds' (added by an over-eager copywriter). She files an Airbnb complaint and refuses to leave. 1-star review."},
      {text:"Charge her £400 per horse per day to use the driveway",pts:-100,good:false,reaction:"She pays it. Then sues you for inadequate facilities to support what she paid for. £18,000 legal fees later, you win the case but lose the relationship."},
      {text:"Let the horses graze on your lawn while you work it out",pts:-260,good:false,reaction:"£3,200 of landscaping destroyed. Hooves through the lawn. The horses are also thirsty and stressed. Animal welfare officer attends. Disaster."},
    ],tip:"Mansion-level bookings can include unusual animals. Have a list of nearby specialist services — equestrian, exotic pet, fine art — on hand before you ever need them."},

    {guest:"The Film Crew",mood:"bohemian 🎥",icon:"🎥",drama:true,scenario:"A film production company has booked your mansion for 8 nights for 'a private retreat'. On day 3 your neighbour calls: 'They've got 40 people, lighting rigs, a smoke machine, and what looks like a movie shoot in your garden. Is this authorised?'",options:[
      {text:"Attend immediately, halt the shoot pending review, demand to see filming permits and your AirCover validation, charge a retrospective £8,000 commercial use fee",pts:240,good:true,reaction:"The production complies — they have permits but didn't disclose to you. £8,000 paid. They request an above-board production booking next month for £35,000. New revenue stream unlocked."},
      {text:"Call the police — this is unauthorised commercial use",pts:80,good:true,reaction:"Police attend. Filming halted. The production leaves bitter. 1-star review. Your council reports you 'mishandled the situation'. Defensible but bruising."},
      {text:"Let it run — it's only 5 more days",pts:-300,good:false,reaction:"£14,000 in damages: scuff marks, paint, rigging holes in the ceiling. Your residential insurance doesn't cover commercial filming. Personal liability."},
      {text:"Negotiate a retroactive licensing fee of £5,000",pts:170,good:true,reaction:"Reasonable middle ground. They accept, pay, and treat the property properly for the rest of the shoot. You add a 'commercial use clause' to your standard listing."},
    ],tip:"Commercial filming requires specific permits, dedicated insurance, and bespoke licensing. Even at the mansion level, residential terms don't cover it."},

    {guest:"The Heiress's Toddler",mood:"oblivious 👶",icon:"👶",drama:true,scenario:"Lady Asquith's grandson, age 3, has just smashed an 18th-century Sèvres vase. Insurance value: £140,000. He's currently smiling at the broken pieces. Lady Asquith says: 'Children will be children. He didn't mean it. We'll be on our way after lunch.'",options:[
      {text:"Stay composed. Document the damage immediately. Engage your specialist contents insurer. Apply for AirCover. Speak with Lady Asquith's family office before she leaves.",pts:280,good:true,reaction:"Family office settles within 8 weeks. Vase replacement (a 1750s match found at Christie's) covered. AirCover covers your excess. Professional resolution. Lady Asquith — once free of the moment — is gracious about it."},
      {text:"Demand £140,000 from Lady Asquith on the spot",pts:-280,good:false,reaction:"She's offended. Her family office goes silent. AirCover excludes 'amounts already disputed in person'. £140k personal loss. Dignified silence would have served you better."},
      {text:"Accept the apology graciously and let it go",pts:-450,good:false,reaction:"Insurance void — failure to log incident. £140,000 personal loss. Lady Asquith never books again anyway. Dignity has its price; in this case £140k."},
      {text:"Politely insist the family contact their personal insurance and yours simultaneously",pts:240,good:true,reaction:"Both insurers engage. The vase is replaced over time. Process well-handled. The Asquith family privately recommend you for handling it 'with grace and competence'."},
    ],tip:"Mansion-level damage requires mansion-level process: photograph, log, claim. Emotion is the enemy of recovery — protocol is your friend."},

    {guest:"The 60-Person Wedding",mood:"festive 💒",icon:"💒",drama:true,scenario:"Bookers have stated 'a small family birthday party — maybe 8 people'. On Saturday at 2 PM your security firm calls: 'There's a wedding ceremony on the lawn. About 60 guests. There's a string quartet.' This was clearly planned for weeks.",options:[
      {text:"Drive to site immediately. Work with the bride and groom (now in dresses) — humanise it. Accept the day for £4,000 retrospective fee but require a damages deposit and curfew",pts:220,good:true,reaction:"The couple are mortified — they thought 'the booking covered it'. They pay the £4k gratefully, the day proceeds. They tip your concierge £1,000. Tearful 5-star review thanking you for not destroying their wedding."},
      {text:"Shut it down — booking terms violated",pts:-160,good:false,reaction:"Bride in tears in the press the next day. 'Heartless host destroyed our day.' Your face on Daily Mail homepage. Eight bookings cancel. Six months to recover."},
      {text:"Threaten police, then accept £2,000 to stay quiet",pts:-220,good:false,reaction:"You appear extortionate. They pay but file a formal complaint. Airbnb investigates. Account warning. Reputation damaged."},
      {text:"Allow it but charge £8,000 retrospectively",pts:140,good:true,reaction:"Steep but fair given they hid the truth. They pay (the wedding budget had cushion). 4-star review: 'Host was strict but professional in the moment.'"},
    ],tip:"Weddings are foreseeable at the mansion level. Build a 'private events package' (£X for up to 30 guests) into your listing — capture the revenue legitimately."},

    {guest:"The Insurance Trap",mood:"calculated 🧐",icon:"🧐",drama:true,scenario:"A guest checks out, then 11 days later files a claim against you for £18,000: 'I broke my hip on your loose stair-tread.' Your CCTV shows him arriving uninjured and leaving uninjured. He has a doctor's note dated 9 days post-stay.",options:[
      {text:"Engage your liability insurer's solicitors immediately. Provide the CCTV. Do not communicate with him directly. Let the legal process play out.",pts:280,good:true,reaction:"His claim collapses in 6 weeks. CCTV is dispositive. He's reported to the Insurance Fraud Bureau — turns out he's tried this 3 times before. Your insurer covers all your costs."},
      {text:"Try to settle privately for £3,000 to make it go away",pts:-340,good:false,reaction:"Settlement is admission. Insurance won't cover further claims. Five future guests file similar claims, having seen yours pay out. Career-altering damage."},
      {text:"Counter-sue him for fraudulent claim",pts:130,good:true,reaction:"Effective deterrent. He withdraws the claim. Your costs partially recovered. Stressful but defensive."},
      {text:"Pay him from your own pocket and learn from it",pts:-380,good:false,reaction:"You've paid a fraudster. He boasts. Three more guests try it. £45,000 paid out within 6 months. Liability spiralling."},
    ],tip:"Continuous CCTV in common areas is non-negotiable at mansion level — for protection of guests, your team, and against fraudulent claims."},
  ],

  // ─────────────────────────────────────────────────────────────────
  // PROPERTY 6 — COVENT GARDEN ROYAL PENTHOUSE
  // ─────────────────────────────────────────────────────────────────
  6: [
    {guest:"Head of State",mood:"protected 🛡️",icon:"🛡️",drama:true,scenario:"A serving European prime minister has booked your penthouse incognito for an 'unofficial visit'. His security detail arrives at 6 AM demanding: ballistic film on every window, scan-and-search of all your staff, removal of any cameras, and a sealed entry log. Your check-in is at 2 PM.",options:[
      {text:"Accommodate fully — defer to their head of security, document via signed protocols, charge the appropriate diplomatic surcharge (£12,000), maintain professionalism throughout",pts:300,good:true,reaction:"Detail is impressed. PM is impressed. Word spreads in protective security circles. Three further heads-of-state bookings within the year. £40,000+ in revenue from this single referral pipeline."},
      {text:"Push back on camera removal — your CCTV is non-negotiable",pts:-180,good:false,reaction:"Security detail terminates the booking. Compensation required. £12,000 lost. Worse: you're flagged in protective security databases as 'non-cooperative'. Future political bookings closed off."},
      {text:"Refuse — too high-stakes for your operation",pts:80,good:true,reaction:"Defensible at the wrong tier. At Covent Garden level, this is your market. You've turned away a £12,000 booking and the door it opens. Lesson learned, no real harm done."},
      {text:"Accept everything but charge an extra £20,000",pts:200,good:true,reaction:"They blink, then accept — they have budget. £20k secured. PM's chief of staff later notes 'good commercial sense'. You've established your value clearly."},
    ],tip:"The Covent Garden tier markets to heads of state, A-list stars, and family offices. Their requirements are not negotiable; your competence and pricing are."},

    {guest:"Oscar's Aftermath",mood:"diva 🎬",icon:"🎬",drama:true,scenario:"An Oscar-winning actress, mid-press tour, demands the entire building be 'silent'. She wants no service staff visible during her stay, the lift programmed for her exclusive use, and the rooftop pool drained 'for energetic clarity'. Booking is 3 nights at £15,000.",options:[
      {text:"Accommodate the silence and lift requests; explain the pool drain (15,000 litres, 3 days, £2,400 cost) is not feasible mid-stay; offer pool covered with floral installation instead",pts:220,good:true,reaction:"She accepts the alternative. The covered pool becomes a stunning Instagram moment. She posts it to 12M followers crediting your venue by name. Bookings spike 80%. £15,000 booking unlocks £200,000 in publicity value."},
      {text:"Drain the pool — she's worth it",pts:-200,good:false,reaction:"15,000 litres of water gone. Pool unusable for the next 3 weeks while refilled and rebalanced. Two other bookings refund partial. Net loss after publicity: £8,000."},
      {text:"Refuse all demands as unreasonable",pts:-150,good:false,reaction:"She cancels and posts a story about 'rude British hosts'. 12M views. PR firms warn HNWI clients. Bookings drop 30% for 2 months."},
      {text:"Counter-offer: silence and lift for £15k as agreed; pool drain for £8k extra",pts:170,good:true,reaction:"She declines the upcharge but respects the structure. Accepts the standard package. Books again 6 months later. Professional respect established."},
    ],tip:"At this tier, eccentric demands are tests of your structure. Accommodate what's reasonable, price what's expensive, refuse what's harmful — calmly and clearly."},

    {guest:"The Diplomatic Incident",mood:"explosive 💥",icon:"💥",drama:true,scenario:"You discover that your two consecutive bookings (4 nights each, back to back) are from senior officials of two countries currently engaged in a public diplomatic dispute. Both arrive within 2 hours of each other. Both delegations spot each other in the lift lobby.",options:[
      {text:"Contact your diplomatic security firm immediately, brief both teams' security on the proximity, offer one delegation an upgrade to your concierge-managed Mayfair penthouse same-night, retain both bookings",pts:280,good:true,reaction:"Both teams appreciate the discretion. The flexibility costs you £2,400 in upgrade. You're paid back in goodwill: both delegations eventually book directly with you for years. Diplomatic discretion is reputation gold."},
      {text:"Cancel one of the bookings to keep the peace",pts:-280,good:false,reaction:"Cancellation penalty: £8,000. The cancelled delegation considers it a slight. Diplomatic note follows. Your name is mentioned in a Foreign Office briefing. Not the kind of fame you wanted."},
      {text:"Let it play out — they're adults",pts:-180,good:false,reaction:"Lobby altercation. Press notification. 'Embassy stand-off in luxury London hotel.' Your property is named. Three months of cancellations from the affected national delegations."},
      {text:"Move the second booking entirely to a sister property at no charge",pts:230,good:true,reaction:"Costs you the differential (£3,200) but defuses a crisis. Both delegations leave grateful. The cancellation desk later sends you a (very British) Christmas card."},
    ],tip:"Vetting bookings at this tier isn't optional — it's a fiduciary duty to your existing relationships. Diplomatic conflict mapping should be part of your booking flow."},

    {guest:"The Wine Catastrophe",mood:"horrified 🍷",icon:"🍷",drama:true,scenario:"Your visiting Michelin chef decants what he believes is a £35 Côtes du Rhône. It's actually a 1929 Romanée-Conti from your pre-revolutionary cellar. Worth £42,000. Your guest, a tech billionaire, was personally looking forward to it.",options:[
      {text:"Personally apologise to the guest. Offer a different £40k+ vintage from your cellar at no cost. Brief the chef on cellar protocols. File an internal incident report.",pts:260,good:true,reaction:"The billionaire is moved by the integrity. 'You actually offered me a replacement of equal value? I don't see that in fine dining.' Books your penthouse for 30 nights/year, indefinitely. Your most valuable client born from a near-disaster."},
      {text:"Hide the bottle — he'll never know what it was supposed to be",pts:-220,good:false,reaction:"His sommelier (yes, he travels with one) identifies the substitution at first sip. He pays in full but never books again. Word spreads in HNWI circles: your wine cellar 'isn't what it claims'."},
      {text:"Blame the chef publicly to deflect",pts:-280,good:false,reaction:"Chef quits citing reputational damage. Sues for breach of professional standards. £18,000 settlement. Your kitchen reputation is now 'volatile'."},
      {text:"Charge him only for the £35 wine and absorb the £42k loss quietly",pts:200,good:true,reaction:"The billionaire's sommelier discreetly informs him afterward. Billionaire is impressed by the quiet absorption. Still books again. Excellent if expensive grace."},
    ],tip:"Pre-revolutionary cellars need locks, logs, and dedicated sommelier protocols. The wines are insured but the relationships aren't."},

    {guest:"The Press Pack",mood:"chaotic 📸",icon:"📸",drama:true,scenario:"Your guest, a tech-billionaire-turned-defendant in a global fraud case, is testifying at the Royal Courts of Justice. 40 paparazzi are now camped outside your private entrance. Tabloids are offering your security team £5,000 each for the lift code.",options:[
      {text:"Engage your diplomatic security team to manage egress, offer the guest a discreet exit through the underground supercar garage, brief all staff on the offer and its consequences",pts:300,good:true,reaction:"Guest exits unphotographed. None of your team takes the bribe (you'd already trained them). One of the offering tabloids reports your team for 'unbreakable culture'. You become the 'go-to' London property for legal high-profile clients. £80k/year niche unlocked."},
      {text:"Try to talk to the press personally to disperse them",pts:-180,good:false,reaction:"You become a media personality overnight, against your interests. Three bookings cancel citing 'concerns about discretion'. Your face is on the news for the wrong reasons."},
      {text:"Let the guest leave through the front door — privacy can't be guaranteed",pts:-220,good:false,reaction:"Photos go global. The guest's lawyers notify yours of 'service inadequacy'. Refund forced. £15,000 booking returned. Reputation hit."},
      {text:"Call the police about the press presence — public obstruction",pts:120,good:true,reaction:"Police clear them within an hour. Effective but blunt. Press grumble; guest grateful. Modest outcome."},
    ],tip:"Underground supercar garages aren't a luxury — at this tier, they're life-saving discreet egress for legally complex clients. Pay the £1,700/month."},

    {guest:"The Theatre Royal",mood:"dramatic 🎭",icon:"🎭",drama:false,scenario:"A famed West End producer wants to host his after-party for 80 industry figures in your private theatre. He'll pay £12,000. He wants performers from his own current production to perform live in your space — they'll require dressing rooms, technical riders, and your sound system 'tweaked'.",options:[
      {text:"Accept with a clear contract: £12k licence fee + £4k production deposit + named technical specifications + 11 PM cutoff + your AV technician on duty",pts:240,good:true,reaction:"The night is legendary. Next morning your theatre and penthouse are featured in The Stage. Three further West End producers contact you for similar events. You've discovered a £100k/year niche."},
      {text:"Decline — too much hassle for £12k",pts:-60,good:false,reaction:"Producer respects the choice ('Too right, dear. Properties at your level are choosy.'). But you've missed an entire niche unlock. Lesson on your scope."},
      {text:"Accept and trust him to manage the technical side",pts:-180,good:false,reaction:"Technical disaster. Sound damage to your theatre system: £14,000. The producer moves on. Insurance disputes coverage. Net loss on a £12k booking: £6,000."},
      {text:"Counter at £20,000 — premium pricing",pts:170,good:true,reaction:"Producer accepts after a thoughtful pause. 'Frankly, this is what proper venues charge.' £20k secured. Tight ship run. Excellent precedent set for your pricing."},
    ],tip:"Specialist private events — theatre, gallery, recording — should each have a published price tier and clear contracts. Negotiate from a structure, not from scratch."},

    {guest:"The False Alarm",mood:"alarmed 🚨",icon:"🚨",drama:true,scenario:"3 AM. Your diplomatic security team alerts: an anonymous bomb threat has been called in to the police, naming your penthouse specifically. Police evacuate the building. Your guest, a Saudi prince, is now standing on the cold pavement at 3:30 AM with his security detail.",options:[
      {text:"Coordinate with police on threat assessment, arrange emergency relocation to your Mayfair penthouse for tonight, brief the prince's detail, document the entire incident formally",pts:280,good:true,reaction:"Threat is found false within 2 hours. Prince is safely at Mayfair by 4 AM. Returns next afternoon. Your handling of the crisis becomes part of his future-stays decision-making. Books for 6 weeks across the year. £80k secured."},
      {text:"Leave it to the police and the security firm — your job is the property",pts:-180,good:false,reaction:"The prince's detail expects you on-scene. Your absence is noted. Booking ends early. The prince's office quietly removes you from their preferred-properties list. Long-term revenue: gone."},
      {text:"Send the prince to a hotel at his cost",pts:-280,good:false,reaction:"Prince's detail is offended. Bills you for hotel and inconvenience. Eight months of legal back-and-forth. £24,000 settlement. Royal-tier reputation: damaged."},
      {text:"Personally arrive to help, even if it's 3 AM",pts:200,good:true,reaction:"You arrive in a coat over pyjamas. Prince's detail respects this enormously. 'You came yourself? At this hour?' Trust earned. Future bookings cement. Sometimes presence is the entire service."},
    ],tip:"At apex tier, your physical presence at the moment of crisis matters more than any operational excellence. Keep a packed bag near the door."},

    {guest:"The Eternal Booking",mood:"committal 💍",icon:"💍",drama:true,scenario:"A reclusive billionaire — your most lucrative ever guest — proposes via his lawyer: £600,000 for 6 months of exclusive booking. His one condition: all other bookings cancelled, no future advertising, your property exits the market entirely for the duration.",options:[
      {text:"Negotiate hard: £900,000 reflecting full opportunity cost; standard cancellation policy applies; clear contract with break clauses; reputation insurance",pts:340,good:true,reaction:"He accepts £750k and your terms. You've secured a year of certainty. Your other property revenues continue. The clean separation protects your platform standing. Best business decision of your hosting career."},
      {text:"Take the £600k — it's a once-in-a-lifetime offer",pts:-280,good:false,reaction:"You cancel 14 confirmed bookings. Penalties total £18,000. AirCover suspends your account for cancellation rate. The billionaire stays 4 months then leaves. £440,000 net after penalties. The account suspension lasts 18 months."},
      {text:"Refuse — you don't put all eggs in one basket",pts:120,good:true,reaction:"Conservative but defensible. You keep your platform standing and other revenues. Maybe a missed opportunity, but no spectacular crash either."},
      {text:"Accept but try to keep some bookings on the side discreetly",pts:-380,good:false,reaction:"He has a private investigator. He finds out within 3 weeks. Contract voided with £200,000 penalty clause. Your reputation in HNWI circles: vapourised."},
    ],tip:"Single-client dependency at this tier is never the right answer — but a fully-priced exclusive can be. Negotiate the structure first; the headline number second."},
  ],
};

// Merge into ALL_QUESTIONS
Object.keys(EXTRA_QUESTIONS).forEach(k => {
  if (!ALL_QUESTIONS[k]) ALL_QUESTIONS[k] = [];
  ALL_QUESTIONS[k] = ALL_QUESTIONS[k].concat(EXTRA_QUESTIONS[k]);
});
